- src/multivariate/mvtdist.jl
- src/utils.jl
This adjusts MvTDist to the refactoring GenericMvNormal->MvNormal.
I also fixed a bug in the function full in utils.jl that I discovered in the process.
> bug fix in MvTDist (replaced GenericMvNormal with MvNormal)

- src/Distributions.jl
GenericMvNormal and GenericMvNormalCanon were removed/renamed during a previous refactoring. However, the names are still exported despite being undefined. This pull requests fixes this.
> removing undefined function names from export list

- src/multivariate/mvtdist.jl
- Fixed _rand! functions so that only one Chisq random variable is sampled for each MvTDist sample (see http://journal.r-project.org/archive/2013-2/hofert.pdf for more details)
- Removed unnecessary MvNormal distributions
> Fixed bug in _rand! functions of MvTDist

- doc/source/index.rst
- doc/source/starting.rst
I followed the style in the DataFrames documentation. Thus, it's intended as a walk-through of the basic features without links to the more detailed documentation. For code blocks, the display differs from the rest of the documentation because I include the ">julia" from the REPL. This is because I want to include both code and output.
Very much looking forward to feedback. Happy to add more or do extensive editing as needed.
> Added 'getting started' to documentation

- src/univariate/continuous/noncentralt.jl
This changes the definition of mean(NoncentralT) so that a non-central T distribution with zero non-centrality parameter produces the same mean as the central T distribution would.
In practice, this reduces to changing the code to pass the following tests:
```
using Distributions
using Base.Test
@test mean(TDist(Inf)) == 0.0
@test mean(NoncentralT(Inf, 0)) == 0.0
```
> [WIP] Fix mean(NoncentralT) when df is Inf

- src/univariate/continuous/laplace.jl
Elapsed times for 400 trials of 2,000,000 iterations:
```julia
import Distributions
function go(r, n)
for _ in 1:n
rand(r)
end
end
function main()
r = Distributions.Laplace()
n = 2000000
rand(r)
for _ in 1:400
@time go(r, n)
end
end
main()
```
> Use `ifelse` for faster `rand(Laplace())`

- src/univariate/continuous/cauchy.jl
- test/fit.jl
Due to an apparent change in the output of iqr(x), this fit method has
been broken for awhile and threw a BoundsError because it expected iqr()
to return two numbers.
This PR restores the functionality of fit(::Cauchy, x), by calling the
quantile function directly. Doing so has the added benefit of getting
the median in the same computation. I've also generalized this fit
method to accept as input x::AbstractArray, not just x::Array.
Finally, I've also added a simple test for this fit method.
> Fix fit(::Cauchy, x)

- src/Distributions.jl
- src/univariate/continuous/biweight.jl
- src/univariate/continuous/epanechnikov.jl
- src/univariate/continuous/levy.jl
- src/univariate/continuous/triweight.jl
- src/univariates.jl
- test/continuous.jl
- test/runtests.jl
This adds a couple of distributions that are commonly used as kernels for kernel density estimation: see http://en.wikipedia.org/wiki/Kernel_(statistics)#Kernel_functions_in_common_use.
I'm not sure if we want these in Distributions, or if they would be better off in another package. Also, the location parameter may be unnecessary.
> add kernel distributions: Epanechnikov, Biweight, Triweight

- src/specialfuns.jl
I was getting many warnings when using `quantile` due to
Inf(Float32/64)
nan(Float32/64)
> removed deprecated inf and nan

- src/truncate.jl
This is a fix to eliminate the ambiguous definition warnings for the Truncated insupport method, noted in #391 to be occurring now in julia 0.4.
The warnings started with pull #374 and were fixed for julia 0.3 with pull #382. Apparently, that previous fix is not working for julia 0.4, and so this one is being proposed to finish the job.  It has been tested on julia 0.3 and 0.4 and seems to eliminate the ambiguous warnings on both.
> Fix ambiguous Truncated insupport method for julia 0.4

- src/univariate/discrete/binomial.jl
- src/univariates.jl
- test/binomial.jl
- test/runtests.jl
This patch should fix issue #384  and adds a quick test case to check consistency of `pdf(Binomial(n,p))` and `pdf(Binomial(n,p), x)`. It also removes a bit of duplicate code in `univariates.jl` by moving it in a helper function `_pdf_fill_outside!`.
> Fix for Issue #384 (pdf of Binomial)

- src/matrix/inversewishart.jl
The present version didn't assume anything about the Wishart matrix so the inverse was calculated with the LU factorization and consequently it was numerically unsymmetric.
> Use Cholesky when inverting random Wishart matrices. Fixes #393

- src/univariate/discrete/poisson.jl
- test/discrete_test.json
As spaceLem, I need a rate of 0 for the Poisson distribution. So I've gone through the distribution code and test scripts, and added in support (and tests) for a rate of 0. This has a v0.9 milestone, and has been sitting around unfixed for almost a year. I hope it's useful to just provide it, otherwise it seems like it may hang around for ever.
Cheers,
Richard.
> Fixing Boundary parameter handling #283 for Poisson(0)

- test/discrete_test.lst
- test/prepdref.py
Merged pull request #398 only added Poisson(0.0) test to json file as I didn't understand how the test suite worked. I've now added it to the right place - thanks @lindahua - and fixed the python code to handle Poisson(0.0) correctly.
> Permanently add Poisson(0.0) to test suite updating #398

- src/Distributions.jl
Title says it all.
This implies precompiling the dependencies for Distributions. We should probably explicit flag all of them as safe for precompilation.
> Allow precompiling Distributions

- src/show.jl
In 0.4, we should use `fieldnames` instead of accessing the `.names` field directly.
Closes #410 .
> Use fieldnames()

- src/univariate/discrete/betabinomial.jl
- src/univariates.jl
* For discrete functions with finite support, calculate
`cdf` from right if we're in the right half of that support
* Remove cdf specialized on `BetaBinomial` (handled by
`DiscreteUnivariateDistribution` version)
* ~~Remove extraneous definitions of `*cdf` functions which simply
convert values to `Int` or `Float64`, where these conversions will
happen in a call to `cdf(...)`~~ See #428
> RFC: Specialize cdf for discrete distributions with finite support

- doc/source/types.rst
Either is typically used for two options. More than two is informal, and sometimes confusing.
Sorry if this is tediously small, it just tripped me up a bit.
> Small grammatical doc change

- src/univariate/discrete/geometric.jl
`params` was untyped for geometric, resulting in fallback for other distributions for which params weren't defined. So something like
```
d = Dirichlet(5, 1)
params(d)
```
resulted in a call here rather than method not found.
> fix type restriction on params function

- src/matrix/inversewishart.jl
- src/matrix/wishart.jl
- src/mixtures/mixturemodel.jl
- src/mixtures/unigmm.jl
- src/multivariate/dirichlet.jl
- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
- src/multivariate/mvtdist.jl
- src/multivariate/vonmisesfisher.jl
- src/testutils.jl
- src/univariate/discrete/noncentralhypergeometric.jl
- test/dirichlet.jl
- test/matrix.jl
- test/mixture.jl
- test/multinomial.jl
- test/mvnormal.jl
- test/mvtdist.jl
- test/noncentralhypergeometric.jl
- test/vonmisesfisher.jl
- Also mixtures and truncated distributions
- Tests enforce contract `typeof(d)(params(d)...) == d` for `isa(d,
Distribution)`
- Similar contracts hold for mixtures and truncated distributions
> added params to multivariate and matrix vars

- REQUIRE
PR https://github.com/JuliaStats/PDMats.jl/pull/37 would need a small change to some typealiases in MvNormal.jl. Therefore fixing upper boundary of PDMats to upcoming version of PDMats (0.4)
The corresponding PR for the same changes in METADATA is https://github.com/JuliaLang/METADATA.jl/pull/4506
> Fix the upper dependency of PDMats

- doc/source/multivariate.rst
- src/Distributions.jl
- src/multivariate/mvlognormal.jl
- src/multivariates.jl
- test/mvlognormal.jl
- test/runtests.jl
A port of my private MvLogNormal class to the Distributions package. Implemented the minimum interface described in the documentation and tested using similar tests as MvNormal.
Implements the same constructors as MvNormal.
No changes to the existing code from the Distributions package (other than includes and exports).
> A multivariate lognormal using MvNormal internally.

- src/univariate/discrete/hypergeometric.jl
- test/discrete_test.json
- test/discrete_test.lst
When `n=0` or `n=ns+nf`, the distribution is degenerated, but still defined.
Improves corner cases support in `FisherExactTest`.
> Hypergeometric: allow `n` to take 0 and ns+nf values

- src/univariate/continuous/betaprime.jl
Fixing bug
```
julia> BetaPrime(3)
ERROR: StackOverflowError:
in call at /Users/jonalm/.julia/v0.4/Distributions/src/univariate/continuous/betaprime.jl:9 (repeats 80000 times)
```
> fixed bug in betaprim constructor for single argument

- src/multivariate/mvnormal.jl
This is roughly twice as fast. Ideally PDMats would wrap Symmetric/Hermitian matrices so the copytri! step would not be necessary, but for reasonably large numbers of data points its cost is negligible anyways.
> Use syrk instead of gemm for computing covariance matrices

- REQUIRE
- src/matrix/inversewishart.jl
- src/matrix/wishart.jl
- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
- src/multivariate/mvtdist.jl
This PR generalizes multivariate distributions dependent on a recent update (JuliaStats/PDMats.jl#41) to PDMats to work with ForwardDiff.jl. 
For `Wishart` and `InverseWishart`, this also depends on (JuliaStats/StatsFuns.jl#6).
Integration tests for desired autodiff behavior are available [here](https://github.com/jmxpearson/distribution_diff_tests).
> generalizing multivariates dependent on PDMats

- src/testutils.jl
`hist` is deprecated in v0.5 so this line threw a lot of warnings in `Pkg.test("Distributions")`
> Replace deprecated call to hist

- REQUIRE
- doc/source/multivariate.rst
- src/Distributions.jl
- src/genericrand.jl
- src/matrixvariates.jl
- src/mixtures/mixturemodel.jl
- src/multivariate/mvlognormal.jl
- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
- src/multivariate/mvtdist.jl
- src/multivariates.jl
- src/samplers/vonmisesfisher.jl
- src/testutils.jl
- src/truncate.jl
- src/univariate/discrete/discreteuniform.jl
- src/univariate/discrete/hypergeometric.jl
- src/univariates.jl
- src/utils.jl
- test/continuous.jl
- test/matrix.jl
- test/mvlognormal.jl
- test/mvtdist.jl
- test/runtests.jl
- test/utils.jl
Companion work to JuliaStats/PDMats.jl#45 to allow for automatic differentiation of logpdfs, etc.
- Removes explicity Float64 casting in MvNormal
- defines a new utility function, `partype` that returns a type capable of holding all the element types of a distribution's parameters
- when `logpdf(d, X)`, etc. are called, the storage array passed to their in-place versions is of type `promote_type(partype(d), eltype(X))`
> logpdfs handle mixed eltype inputs

- REQUIRE
- src/Distributions.jl
- src/samplers/binomial.jl
- src/samplers/gamma.jl
- src/samplers/poisson.jl
- src/univariate/continuous/beta.jl
- src/univariate/continuous/chisq.jl
- src/univariate/continuous/erlang.jl
- src/univariate/continuous/fdist.jl
- src/univariate/continuous/gamma.jl
- src/univariate/continuous/noncentralchisq.jl
- src/univariate/continuous/tdist.jl
- src/univariate/discrete/binomial.jl
- src/univariate/discrete/hypergeometric.jl
- src/univariate/discrete/negativebinomial.jl
- src/univariate/discrete/poisson.jl
- test/mvlognormal.jl
- test/mvnormal.jl
This bumps the StatsFuns dependency to 0.3.0, which provides Rmath stuff. Fixes the libRmath errors on 0.5 and avoids a direct dependency on Rmath.jl.
> Replace references to Rmath with StatsFuns

- src/samplers/vonmises.jl
As per JuliaLang/julia#9569, `randbool()` has been deprecated in favor of `rand(Bool)`.
> Change randbool to rand(Bool) in vonmises sampler

- src/multivariate/mvnormal.jl
- src/univariate/discrete/skellam.jl
- test/mvnormal.jl
- test/runtests.jl
- test/univariates.jl
Adding cdf(d::Skellam, x::Int)
- avoids ambiguity warning in v0.4
> Fix Skellam cdf ambiguity warning

- src/matrix/inversewishart.jl
- src/matrix/wishart.jl
- src/multivariate/multinomial.jl
- src/multivariate/mvlognormal.jl
- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
- src/multivariate/mvtdist.jl
- src/multivariate/vonmisesfisher.jl
- src/utils.jl
- test/matrix.jl
- test/multinomial.jl
- test/mvlognormal.jl
- test/mvnormal.jl
- test/mvtdist.jl
- test/utils.jl
- test/vonmisesfisher.jl
This PR encompasses two sets of changes:
- fleshing out conversions (with tests) for multivariate and matrix-variate distributions that had already been parameterized
- adding the last unparameterized multivariates:
- `MvLogNormal`
- `Multinomial`
- `VonMisesFisher`
On the roadmap to fully parametric, there remains:
1. Fixing remaining hardcoded `Float64`s. In particular:
- aliases like `ZeroMeanIsoNormal` in the multivariates
- code for computing MLEs, where type stability is trickier to think through
1. Truncated distributions
1. Mixtures (though I was under the impression that these were moving out; should this be a priority?)
> more parametric distributions

- src/deprecates.jl
- src/univariate/discrete/betabinomial.jl
- src/univariate/discrete/binomial.jl
This addresses the issue raised in JuliaGraphs/LightGraphs.jl#407. It's entirely reasonable for users to be able to write
```julia
Binomial(1., 0.75)
```
Previously, the inner constructor handled the implicit conversion of the first argument to Int. This just restores that behavior. 
```julia
Binomial(1.5, 0.5)
```
will throw an `InexactError` as before.
> changed binomial to accept generic first argument

- test/REQUIRE
- test/runtests.jl
I've moved all `using` statements to runtests.jl and I've declared all test dependencies in test/REQUIRE. The hope is that this will fix #538 by ensuring that all modules used by tests are precompiled prior to running the tests in parallel.
> Ensure test dependencies are precompiled before distributing tests

- src/Distributions.jl
To avoid warnings about identifier conflicts
> Import dof and span from StatsBase

- src/Distributions.jl
- src/estimators.jl
- src/univariate/continuous/vonmises.jl
Things that we have forgotten to remove at various refactorizations. It could be argued that we should keep the `posterior` definitions but they don't seem to be used much right now and I think they would fit better in something like `BayesianBase`.
Notice: This PR includes the bug fix for `Laplace`. I'll refactor once that PR has been merged.
> Various cleanup

- src/mixtures/mixturemodel.jl
- src/mixtures/unigmm.jl
- test/mixture.jl
Defines support for `UnivariateGMM` using `@distr_support`, and implements `minimum(::MixtureModel)` and `maximum(::MixtureModel)`, since those depend on the individual components. This also adds relevant tests.
> Define support for mixture models

- src/Distributions.jl
- src/utils.jl
In particular, this should fix "could not import Base.scale into Distributions" and the `.+` overloading warning.
> Fix a couple deprecation warnings on 0.6

- src/univariate/continuous/fdist.jl
- test/ref/continuous_test.ref.json
Before:
```
julia> using Distributions
julia> d = FDist(30, 40)
Distributions.FDist{Float64}(ν1=30.0, ν2=40.0)
julia> kurtosis(d)
4.016099071207431
julia> kurtosis(rand(d, 5_000_000))
2.245386630172172
```
After:
```
julia> using Distributions
julia> d = FDist(30, 40)
Distributions.FDist{Float64}(ν1=30.0, ν2=40.0)
julia> kurtosis(d)
2.2442906574394463
julia> kurtosis(rand(d, 5_000_000))
2.2924267619033687
```
Closes #590
> Fix kurtosis calculation for FDist

- src/multivariates.jl
- src/univariates.jl
This results in better type stability in cases where the reduction output is not a `Float64`. I found this while messing about with the [code in this Discourse post](https://discourse.julialang.org/t/julia-static-compilation/296/20) and [a branch of ForwardDiff which adds stack-allocated, low-dimensional gradients](https://github.com/JuliaDiff/ForwardDiff.jl/pull/213).
Note that I found a bunch of places with the same problem throughout the codebase - all of these spots will likely kill performance with non-`Float64` number types like `Dual`.
Setup:
```julia
using BenchmarkTools, ForwardDiff, Distributions
f(x1, x2, D) = loglikelihood(Normal(x1, x2), D)
∇f(x1, x2, D) = ForwardDiff.derivative((y1, y2) -> f(y1, y2, D), (x1, x2))
x1, x2 = rand(2);
D = rand(Normal(5.0, 1.0), 10);
```
Before …
> use Base.sum instead of handrolled sum with poorly initialized accumulator

- src/utils.jl
Clearly I was not sufficiently diligent when initially attempting to fix this, as wrapping the definitions in a version conditional does not get around a warning emitted by the parser. This gets around it by using `include_string`.
> Fix handling of .+ and .- overload deprecation

- REQUIRE
- src/multivariates.jl
- test/mvnormal.jl
This reinstates the previous definition of `loglikelihood` for multivariate distributions that was changed in #592. Unfortunately there were no tests to verify the behavior so an issue went unnoticed. Addresses https://github.com/JuliaLang/METADATA.jl/pull/8848#issuecomment-294328801.
@jrevels Let me know if you have any ideas for a better way to initialize the accumulator or to otherwise approach this.
Fixes  #595
> Revert change to multivariate log likelihood

- doc/source/multivariate.rst
- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
- test/mvnormal.jl
#436 has made using Distributions.jl with POMDPs.jl difficult. Unfortunately completely addressing #436 seems to be a large task since the issue has not been addressed for a long time. To enable the use of some distributions, we have been using [this hack](https://github.com/JuliaPOMDP/POMDPToolbox.jl/blob/master/src/distributions/distributions_jl.jl), which I would like to get rid of. I am wondering if JuliaStats would be amenable to adding the `rng` argument to `rand` for only a subset of distributions. After all, people using POMDPs.jl tend to only use either `MvNormal` or the univariate distributions.
This PR contains the implementation for `AbstractMvNormal`. If you think this is a good idea, I will also add it for some of the univariate distributions.
> rand(rng, d) for certain distributions (starting with MvNormal)

- .travis.yml
- REQUIRE
- src/Distributions.jl
Should get the tests passing on nightly (I hope) since we use FFTs to compute the Poisson binomial PDF that the Base DFT functionality has been removed in 0.7. This requires bumping the required Julia version to 0.6.
> Add dependency on FFTW, bump Julia to 0.6

- src/Distributions.jl
- src/samplers/binomial.jl
- src/samplers/categorical.jl
- src/samplers/poissonbinomial.jl
- src/univariate/discrete/discreteuniform.jl
The latter functions have been deprecated in StatsBase (https://github.com/JuliaStats/StatsBase.jl/pull/279).
> Use rand() and Base.Random.RangeGeneratorInt instead of randi() and RandIntGenerator

- REQUIRE
- src/Distributions.jl
I've opened a PR in StatsBase (https://github.com/JuliaStats/StatsBase.jl/pull/274) to add `params`, so packages can use it without the entire Distributions dependency.  This PR simply imports params from StatsBase, and shouldn't be merged before the other.
> import StatsBase.params

- REQUIRE
- src/Distributions.jl
This reverts parts of #627, to remove the dependency on FFTW, which is currently breaking most usages of Distributions on Julia v0.6. 
I would advocate merging this, tagging, then putting the dependency on `FFTW` back, and tagging a 0.7 only release. 
I release there is no consensus on this approach right now, but I'm putting this out there at the very least for users to patch their systems locally -- use this branch, and delete `FFTW` and `AbstractFFT` from `~/.julia/v0.6/` if you are struggling with precompilation issues around Distributions and FFTW. 
Fix #631
cc: @ararslan @stefankarpinski
> Emergency fix to get distributions to work on 0.6

- src/univariate/discrete/poissonbinomial.jl
- test/poissonbinomial.jl
Avoids having to introduce a dependency on FFTW, which has binary dependencies, just for this one distribution. Distributions is already a pretty heavyweight dependency for packages; FFTW (once it actually works) will only make that worse. Thus I'm proposing this simple, standalone DFT implementation for the Poisson binomial PDF.
> Use a simple DFT algorithm when FFTW is not in Base

- test/poissonbinomial.jl
Need to loosen the tolerance a bit since the algorithm in #641 doesn't retain tolerance to within 10<sup>-15</sup>. This bumps the tolerance to 2×10<sup>-15</sup>.
> Bump the Poisson binomial PDF test tolerance

- src/univariate/discrete/poissonbinomial.jl
- test/poissonbinomial.jl
Also, fix initialization of the `y` vector. (Sorry, Alex)
> Fix precision in _dft by reducing the magnitude of the argument in cis

- src/univariate/continuous/noncentralchisq.jl
- test/vonmisesfisher.jl
Triggered by JuliaLang/julia#22800
> Fixes for changes in nightly

- src/mixtures/mixturemodel.jl
- test/mixture.jl
Fixes #650 and https://github.com/brian-j-smith/Mamba.jl/issues/122
After this fix, https://github.com/brian-j-smith/Mamba.jl is able to perform MCMC on mixture distributions:
> Add insupport method to MixtureModel

- src/truncate.jl
- test/truncate.jl
I have code that somewhere calls `quantile(d, x)` for a user-specified distribution `d` and a value `x` that happens to be `Float32`. At the moment this code works for general univariate distributions but it breaks when `d` is a truncated distribution, as its quantile requires `Float64`. Not sure if enforcing `Float64` is required for any specific reason, but since neither the `quantile` function for non-truncated distributions nor other functions (`pdf` etc.) for truncated distributions are as restrictive, I think the `quantile` function of truncated distributions shouldn't be, either.
Side remark: the whole definition of `Truncated` distributions is hard coded to use `Float64`:
```julia
struct Truncated{D<:UnivariateDistribution, S<:ValueSupport} <: UnivariateDistribution{S} …
```
> make quantile function of truncated distributions accept more than just Float64 arguments

- src/quantilealgs.jl
- test/quantile_newton.jl
- test/runtests.jl
quantile_newton and cquantile_newton find a quantile of a distribution
using Newton's method. However, their convergence will never be
satisfied when the initial point and the mode are the same. For example,
quantile_newton(Normal(0, 1), 0.5) will result in an infinite loop. This
patch fixes the problem by relaxing the convergence criterion.
This must be merged before #665.
> fix infinite loop of Newton's method

- src/samplers/categorical.jl
Makes the return type of `rand(::AliasTable)` inferable, with the associated performance boost.
```julia
using Distributions
x = rand(1000)
d = Categorical(x ./ sum(x))
```
`master`:
```julia
julia> @time rand(d, 1_000_000);
0.240576 seconds (3.17 M allocations: 56.091 MiB, 13.16% gc time)
julia> @time rand(d, 1_000_000);
0.210680 seconds (3.18 M allocations: 56.127 MiB, 0.59% gc time)
julia> @time rand(d, 1_000_000);
0.206656 seconds (3.18 M allocations: 56.128 MiB, 1.55% gc time)
```
This PR:
```julia
julia> @time rand(d, 1_000_000);
0.035367 seconds (11 allocations: 7.661 MiB)
julia> @time rand(d, 1_000_000);
0.036287 seconds (11 allocations: 7.661 MiB)
julia> @time rand(d, 1_000_000);
0.041560 seconds (11 allocations: 7.661 MiB, 15.54% gc time)
```
> Make AliasTable.isampler type concrete

- src/samplers/categorical.jl
- test/locationscale.jl
Fixes #671. Supersedes #674.
Also fix a vectorization in tests to avoid a warning
> Revert a tiny part of #655

- src/Distributions.jl
- src/functionals.jl
- test/binomial.jl
The `pmf` function is exported in `Distributions.jl` but not defined anywhere. If I understand correctly, there is a move towards using `pdf` for discrete as well as continuous distributions and this name should no longer be exported.
> Stop exporting `pmf`.

- src/univariate/discrete/binomial.jl
I don't think these Float64s are needed and prevent users from evaluating binomial pdf with e.g. BigFloat.
> Remove legacy Float64s

- src/truncated/normal.jl
- test/runtests.jl
- test/truncnormal.jl
The previous implementation had trouble when the truncation ocurred away from the mode of the distribution. This commit fixes that.
Fixes https://github.com/JuliaStats/Distributions.jl/issues/690.
See https://github.com/cossio/TruncatedNormal.jl/blob/master/notes/normal.pdf for explanation.
Test values were obtained with arbitrary precision in Mathematica.
> fix mean and var of trunc normal

- REQUIRE
It is only used in tests and already in `test/REQUIRE`.
> Remove Calculus from REQUIRE

- src/multivariate/mvnormal.jl
This issue was revealed when 32 bit windows testing was enabled.
> Change Int64 to Integer in rand for MvNormal to avoid wrong dispatch on 32 bit systems

- src/multivariate/mvnormal.jl
- test/mvnormal.jl
> Add constructors for MvNormal with Symmetric and Diagonal matrices.

- docs/src/starting.md
- src/mixtures/mixturemodel.jl
- test/mixture.jl
An undef had been forgotten in `var` for Univariate mixtures
> line break, fix undef

- src/common.jl
Complete some lacking docstring, especially in the `common.jl` interface, core info should be available from the REPL. Fixes #744
> complete docstrings

- src/multivariate/mvtdist.jl
- test/mvtdist.jl
This adds tests for `rand` for `MvTDist` (the size of the result at least) and fixes a bug in the MvTDist rand method where `sqrt(::Vector)` should be `sqrt.(::Vector)`.
> fix missing broadcast sqrt in MvTDist rand

- docs/src/univariate.md
- src/Distributions.jl
- src/univariates.jl
- test/categorical.jl
- test/locationscale.jl
- test/mixture.jl
- test/poissonbinomial.jl
- test/semicircle.jl
- test/truncate.jl
- test/univariates.jl
- test/utils.jl
Replaces #756, which needlessly created methods for specific `UnivariateDistribution` types.
Includes tests and docs.
> Base.extrema methods for UnivariateDistribution and for RealInterval (take 2)

- docs/src/starting.md
┌ Warning: `quantile(d::UnivariateDistribution, X::AbstractArray)` is deprecated, use `quantile.(d, X)` instead.
│   caller = top-level scope at none:0
└ @ Cor
> Update to use broadcasting per warnings

- src/multivariate/mvnormal.jl
- test/mvnormal.jl
gives a simple constructor overload for `MvNormal` to support `LinearAlgebra.I` for setting the sigma matrix.
> Add support for LinearAlgebra.I fixes #784

- docs/src/extends.md
- docs/src/types.md
- src/common.jl
- src/mixtures/mixturemodel.jl
Removes strict coupling between continuous/discrete distributions and support types, as discussed in #681.
No actual new code here, just an update to the the docs to flag the assumptions about support types of different distributions and the ability to override the defaults. The `eltype(::Type{<:ValueSupport})` methods are unused and wouldn't be accurate anyways in the case of an override, so they're removed.
This sets the stage for allowing discrete non-integer-support distributions (e.g. #634 and #661).
> RFC: Officially allow/document overriding distribution support type

- test/qq.jl
These tests were failing on my local machine even though the array elements were printing as identical, presumably an issue with floating point rounding error. Replacing `==` with `≈` fixed the problem.
> Replace equality with approximate equality in qq tests

- src/samplers/aliastable.jl
- src/samplers/discretenonparametric.jl
- src/univariate/discrete/discretenonparametric.jl
Enables
```julia
rand(::AbstractRNG, ::DiscreteNonParametric)
rand(::AbstractRNG, ::DiscreteNonParametricSampler)
```
in addition to the existing methods that default to using `Random.GLOBAL_RNG`.
> Allow providing an RNG for DiscreteNonParametric sampling

- src/univariate/discrete/discretenonparametric.jl
- test/discretenonparametric.jl
This allows calling `DiscreteNonParametric(xs, ps, NoArgCheck())` without providing explicit type parameters. My understanding is that we need to keep the type parameters on the inner constructors to support `Categorical` type aliasing.
> Add DiscreteNonParametric NoArgCheck method

- src/univariate/discrete/negativebinomial.jl
As highlighted in #474, the Wikipedia definition of the negative binomial distribution, linked in the docstring, is not consistent with the definition used in Julia. In this PR, I attempt to remove the source of confusion.
> Update NegativeBinomial external link in docstring

- src/univariate/discrete/bernoulli.jl
No need for a dichotomy outcome to use `Int` instead of `Bool`.
> Bernoulli sampler to Bool

- src/truncate.jl
- src/truncated/uniform.jl
- test/truncate.jl
- test/truncated_uniform.jl
This is implemented by making `Truncated(::Uniform, ...)` return a
`Uniform`.
The advantage is that no other functionality needs to be duplicated.
A minor style infraction is a `T(...)` function not constructing a `T`
object, but I think in this case this is a reasonable compromise.
> Add special case for truncating Uniform.

- Project.toml
- REQUIRE
- src/Distributions.jl
- test/REQUIRE
- test/discretenonparametric.jl
- test/runtests.jl
- test/testutils.jl
as an alternative to https://github.com/JuliaStats/Distributions.jl/pull/863, I think this is a cleaner way
* add `Distributed` to `Project.toml` and delete `REQUIRE` -- no longer required if I understand it right.
* add `compat` section according to the contents in `REQUIRE`
* items in `Project.toml` are listed in alphabetical order
* move `src/testutils` to `test/testutils` to reduce package dependency. This also fixes issue https://github.com/JuliaStats/Distributions.jl/issues/864
cc:@gustafsson 😄
> [RFC] Update Project.toml and move testutils to test/

- Project.toml
In preparation for the next release. I'd really like to get out a release ASAP to get rid of the Test dependency warning.
> Set version to 0.19.2

- Project.toml
Due to a bug in Registrator, we can't register a new version of Distributions until either the bug is fixed or we remove `[compat]` entries for test-only dependencies. See #868 and https://github.com/JuliaComputing/Registrator.jl/issues/110.
> Remove test-only dependencies from [compat]

- src/utils.jl
Flux tracked arrays do not work with the `isprobvec` and `allnonneg` functions as they are. I changed the type definitions to accept abstract vectors and abstract arrays.
> loosen type restrictions to accept accept variants

- src/univariate/continuous/normal.jl
- test/continuous.jl
I didn't see any similar tests so I'm not sure if this needs any tests. I don't imagine that fixing the `eltype` would be particularly breaking (although it is changing the output type of `rand(n::Normal, dims)`).
However, the fix for the single `rand` return type could change an incorrect return type into an error, if the `eltype` of the Normal dist. doesn't support `randn`. I noticed this when using DoubleFloats (prior to v0.8.1 of DoubleFloats.jl).
```julia
julia> n = Normal(Double64(1), Double64(0.1))
Normal{DoubleFloat{Float64}}(μ=1.0, σ=0.1)
julia> x = rand(n)
0.9972028245261662
julia> typeof(x)
DoubleFloat{Float64}
julia> n32 = Normal(1f0, 0.1f0)
Normal{Float32}(μ=r1.0f0, σ=0.1f0)
julia> x32 = rand(n32)
0.9335312783262796
julia> typeof(x32)
Float64
julia> n = Normal(Double64(1), …
```
> Fix #894 Normal distribution and its type parameter

- src/matrix/inversewishart.jl
- src/matrix/wishart.jl
- test/wisharts.jl
`convert` doesn't work for `Wishart` and `InverseWishart`. 
MWE:
```julia
using Distributions, LinearAlgebra
d = Wishart(Float32(10), Matrix{Float32}(I, 3, 3))
g = InverseWishart(Float32(10), Matrix{Float32}(I, 3, 3))
```
Then
```julia
julia> convert(Wishart{Float64}, d)
ERROR: MethodError: no method matching AbstractArray{Float64,2}(::PDMats.PDMat{Float32,Array{Float32,2}})
Closest candidates are:
AbstractArray{Float64,2}(::SymTridiagonal) where T at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/tridiag.jl:94
AbstractArray{Float64,2}(::Tridiagonal) where T at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/tridiag.jl:629
AbstractArray{Float64,2}(::LinearAlgebra.QRPackedQ{T,S} where …
```
> Fix `convert` method for `Wishart` and `InverseWishart`

- src/Distributions.jl
- src/convolution.jl
- test/convolution.jl
- test/runtests.jl
These are simple functions to convolve distributions where a closed form exists. 
Edit: taken essentially from this list: https://en.wikipedia.org/wiki/List_of_convolutions_of_probability_distributions
Please advise if this is the correct place to put them or if somewhere else would be more suitable.
> functions to convolve simple distributions

- src/univariate/continuous/tdist.jl
- test/edgecases.jl
- test/runtests.jl
#929 wants `rand( TDist(Inf) )` to return standard normal draws like it used to (currently returns `NaN`). This PR brings that back, and also introduces unit tests for confirming that `TDist(Inf)` behaves like `Normal(0,1)` in other ways: `mean`, `var`, `pdf`, etc. They currently *do not* agree on `entropy`, `gradlogpdf`, `cf`. Not sure if/how we want to handle that. Let me know.
> Make TDist(Inf) behave like Normal(0,1) (addresses Issue #929)

- docs/src/matrix.md
- src/matrix/inversewishart.jl
- src/matrix/matrixbeta.jl
- src/matrix/matrixnormal.jl
- src/matrix/matrixtdist.jl
- src/matrix/wishart.jl
Bring the documentation of `Wishart` and `InverseWishart` up to the standard of the documentation for [`FDist`](https://juliastats.github.io/Distributions.jl/stable/univariate/#Distributions.FDist), [`MvNormal`](https://juliastats.github.io/Distributions.jl/stable/multivariate/#Distributions.AbstractMvNormal), [`MatrixNormal`](https://juliastats.github.io/Distributions.jl/latest/matrix/#Distributions.MatrixNormal), [`MatrixBeta`](https://juliastats.github.io/Distributions.jl/latest/matrix/#Distributions.MatrixBeta), etc.
> upgrade matrix-variate docs

- src/matrix/inversewishart.jl
- src/matrix/matrixbeta.jl
- src/matrix/matrixnormal.jl
- src/matrix/matrixtdist.jl
- src/matrix/wishart.jl
- test/matrixnormal.jl
Following suggestions made on JuliaStats/Distributions.jl#935, moves type names to the top of docstrings and eliminates extra whitespace.
> matrix-variate cleanup

- docs/src/matrix.md
- src/Distributions.jl
- src/matrix/matrixfdist.jl
- src/matrixvariates.jl
- test/matrixfdist.jl
- test/runtests.jl
Implements the basic features of the matrix *F*-distribution. See [here](https://projecteuclid.org/euclid.ba/1515747744), and also the "generalized beta type II" distribution in chapter 5 of [Gupta and Nagar (1999)](https://www.crcpress.com/Matrix-Variate-Distributions/Gupta-Nagar/p/book/9781584880462).
(This would also make use of JuliaStats/StatsFuns.jl#72 in the long-run.)
> Add `MatrixFDist`

- Project.toml
- src/multivariate/mvtdist.jl
- test/mvtdist.jl
In my continuing quest to use static arrays in distributions, this widens the
mean of GenericMvTDist to be any `<:AbstractVector`, and adds a type parameter
to indicate the actual type.  I didn't widen the "convenience constructor"
methods, so anyone not calling the (un-exported) `GenericMvTDist` constructor
directly shouldn't be affected by this.
> Allow AbstractVector for mean of MvTDist

- docs/src/multivariate.md
- src/Distributions.jl
- src/multivariate/product.jl
- test/product.jl
Without this in the current situation, one would have to abuse the `Product` constructor to create specialized distributions
> added product-function

- Project.toml
- src/univariate/discrete/poissonbinomial.jl
- test/poissonbinomial.jl
This PR enables forward differentiation through the `PoissonBinomial` distribution.
> Make PoissonBinomial support ForwardDiff

- src/multivariate/product.jl
- test/product.jl
Currently insupport is not defined for distributions constructed with product_distribution, e.g.
```
prod = product_distribution([Uniform(0,1), Uniform(2,3)])  
insupport(prod, [0.5, 2.5]) 
```
yields:
```
ERROR: MethodError: no method matching insupport(::Product{Continuous,Uniform{Float64},Array{Uniform{Float64},1}}, ::Array{Float64,1})
```
This does work for a product of Normal distributions however, since the MvNormal constructor is called instead.
I fixed the problem with:
```
insupport(d::Product, x::AbstractArray) = all(insupport.(d.v, x))
```
Hopefully that's the intended behaviour of product distributions.
> Added insupport for Product-type distributions

- src/multivariate/multinomial.jl
- src/samplers/multinomial.jl
- test/multinomial.jl
This PR makes the `Multinomial` distribution support `Tracker` AD. Here is an example that works with this PR but not on `master`:
```julia
using Tracker, Distributions
Tracker.gradient((p) -> logpdf(Multinomial(2, p / sum(p)), [2, 0]), fill(0.5, 2))
```
> Make Multinomial support Tracker AD

- src/truncate.jl
- src/truncated/normal.jl
- src/truncated/uniform.jl
- test/poissonbinomial.jl
- test/testutils.jl
- test/truncate.jl
This PR allows autodiff to be used with `Truncated` to find the derivative of the `logpdf` function wrt to any of the continuous parameters of `Truncated`.
> Make Truncated support autodiff

- docs/src/multivariate.md
- docs/src/types.md
- src/Distributions.jl
- src/common.jl
- src/multivariate/dirichlet.jl
- src/multivariate/mvlognormal.jl
- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
- src/multivariate/mvtdist.jl
- src/multivariates.jl
- src/univariate/continuous/normal.jl
- src/univariate/discrete/discretenonparametric.jl
- src/utils.jl
- test/continuous.jl
- test/mixture.jl
- test/testutils.jl
- test/types.jl
- test/utils.jl
Currently `eltype` is implemented for instances instead of types, although [according to the documentation](https://docs.julialang.org/en/v1/base/collections/#Base.eltype)
>  the form that accepts a type argument should be defined for new types.
I noticed this issue when I tried to implement a sampling algorithm as an iterator by following the example in the [documentation](https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-iteration-1) which advises to implement `eltype(IterType)`. Due to the missing implementation of `eltype` for types in Distributions.jl an implementation such as `eltype(::Type{<:CustomIterator{S}}) where S = eltype(S)` just leads to an element type of `Any`.
(BTW, even if the type-based implementation is added, Distributions.jl still requires some …
> Implement `eltype` for types instead of instances

- src/multivariate/mvnormal.jl
- test/mvnormal.jl
Fixes the issue #995 and also makes MvNormal accept Diagonal matrices. I additionally updated the tests. 
I'm new to Julia and never made a pull request before so please let me know if I can do anything to improve this pull request.
> Make MvNormal accept Symmetric and Diagonal matrices

- src/univariate/discrete/discretenonparametric.jl
- test/discretenonparametric.jl
Fixes #1017 
Changes:
- Add condition `i < length(p)` to while loop in `rand(DiscreteNonParametric)`
> Fixes out of bounds error for loop in rand(DiscreteNonParametric)

- Project.toml
- src/Distributions.jl
- src/multivariate/mvlognormal.jl
- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
- src/multivariate/mvtdist.jl
- src/utils.jl
- test/convolution.jl
- test/mvlognormal.jl
- test/utils.jl
Fixes https://github.com/JuliaStats/Distributions.jl/issues/833.
> Replace ZeroVector with Zeros from FillArrays

- docs/src/starting.md
- docs/src/truncate.md
- src/Distributions.jl
- src/truncate.jl
- src/truncated/normal.jl
- src/truncated/uniform.jl
- test/ref/continuous_test.ref.json
- test/truncate.jl
- test/truncated_exponential.jl
- test/truncated_uniform.jl
- test/truncnormal.jl
- test/univariates.jl
Just like https://github.com/JuliaStats/Distributions.jl/pull/975 but for `Truncated`
Sadly Base already exports `truncate` so we had to settle with `truncated(::D, lower, upper)`
> Truncate generic

- src/univariate/discrete/categorical.jl
- src/univariates.jl
- test/categorical.jl
Found another literal `Inf` in the wild. There was also a redundant `logpdf` method for `Categorical`.
> Fix a type instability issue for logpdf(::Categorical)

- src/univariate/discrete/categorical.jl
- test/categorical.jl
This will make it easier to use the distribution in broadcasting. It made me wonder if we should deprecate the `Categorical(::Int)` constructor since it's tangentially ambiguous (although not ambiguous to the compiler.) Notice that I made this PR on top of the small fix in #1028.
I also wondered if we eventually should change the internal representation of `Categorical` to use a `Tuple` instead of `Vector` and then use the varargs constructor as the only allowed interface. It would both make the distribution much more efficient and, in my opinion, easier to use. The only issue would be if people often use `Categorical`s with a lot of outcomes. In any case, that is a PR for another day.
> Add varargs constructor for Categorical

- src/samplers/poisson.jl
- src/univariate/discrete/poisson.jl
I noticed that `sampler` is not implemented for Poisson distributions although two native samplers `PoissonCountSampler` and `PoissonADSampler` exist. Moreover, currently R is used for sampling from Poisson distributions, [which is quite slow](https://github.com/JuliaDiffEq/PoissonRandom.jl/issues/6). For now I used the same cut-off value of 6 for both samplers, as chosen in [PoissonRandom.jl](https://github.com/JuliaDiffEq/PoissonRandom.jl).
I repeated the benchmarks
```julia
using Distributions, PoissonRandom, StatsFuns
using Plots
function n_count(rng, λ, n)
tmp = 0
for i in 1:n
tmp += PoissonRandom.count_rand(rng,λ)
end
tmp
end
function n_pois(rng,λ,n)
tmp = 0
for i in 1:n
tmp += pois_rand(rng,λ)
end
tmp
end
function n_ad(rng, λ, n)
tmp = 0
for i in 1:n
tmp += …
```
> Use native samplers for Poisson distribution

- src/matrix/matrixbeta.jl
- src/matrix/matrixfdist.jl
JuliaStats/StatsFuns.jl#72 has been merged and released, so it can be used when computing the integrating constants of the Matrix-Beta and Matrix-F distributions.
> use logmvbeta in MatrixBeta and MatrixFDist

- src/multivariate/mvnormal.jl
- test/mvnormal.jl
There exist different issues about inconsistencies in the constructor of `MvNormal` (see, e.g., https://github.com/JuliaStats/Distributions.jl/issues/584 and https://github.com/JuliaStats/Distributions.jl/issues/826). It caught me by surprise (https://github.com/TuringLang/Turing.jl/issues/991) that actually
```julia
MvNormal(ones(3), 3 * I) != MvNormal(ones(3), Matrix(3 * I, 3, 3))
```
I would have assumed that `3 * I` is treated liked other matrices as a proper covariance matrix. IMO the current behaviour of
```julia
MvNormal(ones(3), 3 * I) == MvNormal(ones(3), 3)
```
is unintuitive (which, of course, is also due to the fact that vectors and scalars are treated as standard deviations - I assume to be more consistent with the constructor of `Normal`). This PR changes this behaviour and …
> [Breaking] Treat `UniformScaling` in constructor of `MvNormal` as matrix

- perf/mixtures.jl
- src/mixtures/mixturemodel.jl
- test/mixture.jl
The performance of mixture models is terrible at the moment, as proved in the added `perf/mixtures.jl` file.
Here are the result:
```julia
julia> include("mixtures.jl")
[ Info: sampling 0.5331830160438613
[ Info: evaluate_manual_pdf
75.281 ns (3 allocations: 80 bytes)
[ Info: current_master
470.505 ns (15 allocations: 272 bytes)
[ Info: improved_version
553.541 ns (9 allocations: 192 bytes)
[ Info: improved_no_inbound
584.072 ns (9 allocations: 192 bytes)
[ Info: improved_zipped
377.395 ns (5 allocations: 112 bytes)
[ Info: improved_indexed
263.629 ns (5 allocations: 112 bytes)
[ Info: sampling 0.4540291355871424
[ Info: evaluate_manual_pdf
75.168 ns (3 allocations: 80 bytes)
[ Info: current_master
470.010 ns (15 allocations: 272 bytes)
[ Info: improved_version
569.508 ns (9 allocations: …
```
> improved mixture

- src/univariate/continuous/lognormal.jl
- test/lognormal.jl
- test/runtests.jl
I noticed some type-instabilities in the current implementation of (log)pdf for `LogNormal`, and tried to fix them.
I adapted the type inference tests for `Normal` distributions. In these tests degenerate normal distributions (with zero variance) are used quite often, hence to simplify the transfer of the tests and for consistency I also allowed the use of degenerate log normal distributions.
This PR fixes https://github.com/JuliaStats/Distributions.jl/issues/456.
> Fix typestability of (log)pdf, (log)cdf, (log)ccdf, and gradlogpdf for LogNormal

- src/multivariate/mvnormal.jl
`UnitWeights` from StatsBase are by default `AbstractVector{Int}` IIRC.
With them all being `1`
Requiring things to be `AbstractArray{Float64}` or worse `Array{Float64}` is just excessive
> relax type constraints on weights for fitting MVNormal

- Project.toml
- src/matrix/inversewishart.jl
- src/matrix/matrixfdist.jl
- src/matrix/matrixnormal.jl
- src/matrix/matrixtdist.jl
- src/matrix/wishart.jl
- test/matrixnormal.jl
- test/matrixtdist.jl
The matrix-variates commit many small sins that make them incapable of handling `AbstractPDMat` subtypes other than `PDMat`. This PR fixes that:
- Allow the two posdef matrices in `MatrixNormal` and `MatrixTDist` to be different types;
- Don't implicitly assume a `PDMat` by hard-coding direct access to fields like `.mat` and `.chol.L`;
- Use the new `kron` methods in `PDMats.jl`;
- ~~Temporary workaround for the fact that not all `AbstractPDMat` subtypes have `\` defined such that `S \ M'` will work (not everyone's `\` plays nice with `Adjoint`)~~.
(Shout-out to @willtebbutt, who [nailed](https://github.com/JuliaStats/Distributions.jl/pull/917#discussion_r297628281) this issue from the start, but I completely misunderstood what he was asking at the time.)
> improve pdmat usage in the matrix-variates

- Project.toml
- src/univariate/discrete/bernoulli.jl
- test/bernoulli.jl
This effectively reverts #1048 and also addresses the original issue #984.
I'm not that familiar with this codebase, but it appears that `rand(D, ...)` uses the `eltype` of the distribution to create the right array container. For `Bernoulli`, `eltype` hit a fallback method that incorrectly returned `Int64`, so changing that to `Bool` fixes the issue.
> Make Bernoulli produce Bools

- src/univariates.jl
This PR makes `minimum(Normal{Float64})` work where previously only `minimum(Normal)` would.
> fix distr_support macro for type parameters

- src/matrix/wishart.jl
- src/utils.jl
- test/matrixvariates.jl
- test/utils.jl
This PR adds the [singular branch](https://en.wikipedia.org/wiki/Wishart_distribution#The_range_of_the_shape_parameter) of the Wishart distribution. That is, for integer `df < p`, the Wishart is a distribution over rank-`df` positive semidefinite `p x p` matrices, defined in the [usual way](https://en.wikipedia.org/wiki/Wishart_distribution#Definition).
In this case the Wishart does not have a Lebesgue density, but it does have a density with respect to an appropriate dominating measure on rank-`df` positive semidefinite matrices, which is given in Theorem 6 [here](https://projecteuclid.org/euclid.aos/1176325375). The usual density in the full rank case is a special case of this "generalized" density.
I am currently implementing this by extending the behavior of `Wishart` instead of …
> Add singular branch of the Wishart

- Project.toml
- src/mixtures/mixturemodel.jl
- test/mixture.jl
Closes #1060 
Adds a method to `var` function which takes a multivariate mixture model as the argument, expanding the current which only accepts univariate mixture models.
Implementation is based on the `cov` function so should be robust.
> define var for multivariate mixture models

- src/matrix/matrixbeta.jl
This PR removes the Wishart type constraint from the MatrixBeta type. I understand the appeal of the type constraint but in DistributionsAD.jl we define our own version of Wishart that I want to use in MatrixBeta. The type constraint makes it impossible to do so. Defining an AbstractWishart is another option but maybe overkill.
> Remove Wishart type constraint from MatrixBeta

- src/univariates.jl
- test/lognormal.jl
- test/normal.jl
This PR loosens the type annotations of `logdiffcdf` and uses `log1mexp` in its computations.
> Use `log1mexp` in the computations of `logdiffcdf`

- docs/src/extends.md
I was implementing a distirbution today, [PERT-Beta](https://en.wikipedia.org/wiki/PERT_distribution).
and I gut up to implementing my sampler, and i found it was erroring.
Then i looked at all the existing distributions and realized that they were implementing the two arg version of rand.
> When implementing a Sampler you need to implement 2 arg rand

- src/univariate/discrete/discretenonparametric.jl
- test/discretenonparametric.jl
Fixes https://github.com/JuliaStats/Distributions.jl/issues/1105.
The problem in the current implementation is the check `cp < draw`: if the probability of the first value is 0 and if `draw == 0.0`, the loop will stop immediately and the first element will be returned even though it has zero probability. When sampling with `Float32` the problem described in the issue linked above becomes apparent. Changing the comparison to `cp <= draw` fixes the problem.
> Fix `rand(::DiscreteNonParametric)` with values of zero probability

- docs/src/extends.md
- docs/src/multivariate.md
- docs/src/univariate.md
- src/multivariates.jl
- src/univariates.jl
- test/locationscale.jl
- test/mvnormal.jl
This PR generalizes `loglikelihood` and adds supports for all possible sample types, i.e., `Real` and `AbstractArray` for univariate distributions and `AbstractVecOrMat` and `AbstractArray{<:AbstractVector}` for multivariate distributions.
Additionally, I updated the documentation and added some tests.
> Support all possible outputs of `rand` in `loglikelihood`

- src/Distributions.jl
- src/univariate/continuous/skewnormal.jl
- src/univariates.jl
- test/runtests.jl
- test/skewnormal.jl
Add SkewNormal distribution based on: 
* [Skew normal distribution on Wikipedia](https://en.wikipedia.org/wiki/Skew_normal_distribution)
* [Discourse](https://discourse.julialang.org/t/skew-normal-distribution/21549/7)
* [SkewDist.jl](https://github.com/STOR-i/SkewDist.jl)
> Add SkewNormal distribution 

- Project.toml
- src/Distributions.jl
- src/samplers/aliastable.jl
- test/categorical.jl
This is needed to get reproducible sampling of `Distributions.Categorical` across Julia versions using `StableRNG` generators. 
Context: https://github.com/JuliaStats/StatsBase.jl/pull/576, https://github.com/rfourquet/StableRNGs.jl/issues/4#issuecomment-674497714
> Remove use of deprecated Random.RangeGenerator for reproducibility across Julia versions

- src/univariate/discrete/geometric.jl
Really sorry @andreasnoack but I think my suggested solution here was the wrong one. This implementation breaks type stability of the method.
I'm actually not even sure Distributions does the wrong thing here, so I suggest simply reverting. I've handled the StatsPlots issue downstream.
This reverts commit 82120fcb8b51e0e3f5789b7ae78a9f9aa8ad2375.
> Revert "Return an Int from `invlogccdf` on Geometric"

- src/matrixvariates.jl
- src/multivariates.jl
- test/matrixvariates.jl
This PR adds `loglikelihood` implementations for `MatrixDistribution`, consistent with the existing behaviour for uni- and multivariate distributions (see https://github.com/JuliaStats/Distributions.jl/pull/1144). It also simplifies the implementation of `loglikelihood` for `MultivariateDistribution` and ensures that `_logpdf` is only called if the dimension was checked before.
> Add `loglikelihood` for `MatrixDistribution`

- src/univariate/discrete/discretenonparametric.jl
```julia
julia> x = rand(2,3)
2×3 Array{Float64,2}:
0.626575  0.277653  0.132907
0.830829  0.489369  0.379038
julia> y = softmax(x;dims=1)
2×3 Array{Float64,2}:
0.449113  0.447268  0.438776
0.550887  0.552732  0.561224
julia> [Categorical(m;check_args=false) for m in eachcol(y)]
ERROR: MethodError: no method matching SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}(::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true})
Closest candidates are:
SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}(::Any, ::Any, ::Any, ::Any) where {T, N, P, I, L} at subarray.jl:19
Stacktrace:
...
```
> Fix conversion error with DiscreteNonParametric

- src/multivariate/dirichlet.jl
- test/samplers.jl
since it's not accurate for too small values.
Initialize arrays in fit_mle for Dirichlet.
Add debug keyword to fit_mle for Dirichlet and fix debug branches
in `fit_dirichlet!`
The initialization bug was the one that caused the test failure in https://github.com/JuliaStats/Distributions.jl/pull/1164 on 32 bit. It's a bit surprising that we haven't hit it more frequently since the initial values were often completely off because of the this, e.g.
```julia
julia> Distributions.dirichlet_mle_init(x)
3-element Array{Float64,1}:
-0.0
-0.0
-0.0
julia> Distributions.dirichlet_mle_init(x)
3-element Array{Float64,1}:
5.158988734525853e104
8.769340308733536e104
-0.16535356495305348
julia> Distributions.dirichlet_mle_init(x)
3-element Array{Float64,1}:
5.040668036024078e103
8.579050171199378e103 …
```
> Stop testing PoissonADSampler for μ=5.0

- src/multivariate/mvnormalcanon.jl
The `PDSparseMat` struct is defined behind a `HAVE_CHOLMOD` flag which is false when people build Julia without GPL libraries, see https://github.com/JuliaStats/PDMats.jl/blob/d50e35a37d218f0e6ac552512bc4c79b102cc930/src/PDMats.jl#L51-L53. Hence, https://github.com/JuliaStats/Distributions.jl/pull/855 broke Distributions when Julia has been built without GPL libraries.
cc @ElOceanografo
> Make new unwhiten_winv! conditional on PDSparseMat

- src/samplers/vonmisesfisher.jl
- test/vonmisesfisher.jl
Resolves #1161 
Had some free time so I just implemented it right away lol
> Optimize vMF sampling

- src/univariate/discrete/poissonbinomial.jl
- test/poissonbinomial.jl
I have done a lot of research in evaluating poisson binomial pmf in last 3 years. The simplest and fastest continues to be the recursive formula. I've cited Thomas & Taub (1982) but it predates this article as well because it is related to evaluating the elementary symmetric function. The Hong (2013) article does a very bad job at evaluating and comparing their method 
```julia
julia> x = [3.5118, .6219, .2905, .8450, 1.8648]
julia> p = big.(x) ./ (1 .+ big.(x))
julia> @benchmark poisbin_sum_taub(p)
BenchmarkTools.Trial: 
memory estimate:  10.20 KiB
allocs estimate:  230
--------------
minimum time:     7.075 μs (0.00% GC)
median time:      7.525 μs (0.00% GC)
mean time:        9.559 μs (12.27% GC)
maximum time:     2.087 ms (66.47% GC)
--------------
samples:          10000
evals/sample: …
```
> Faster, more accurate Poisson Binomial PMF

- src/matrix/matrixnormal.jl
I was just browsing the source code and saw a couple missed opportunities for broadcast fusion. I did some quick benchmarking and in both cases it saves a couple microseconds and allocations.  
```julia
julia> @btime _rand!($rng, $d, $X);
22.679 μs (5 allocations: 32.63 KiB)
julia> @btime _rand2!($rng, $d, $X);
22.065 μs (4 allocations: 24.69 KiB)
```
```julia
julia> @btime _rand_params(MatrixNormal, Float64, 100, 100);
169.032 μs (25 allocations: 704.02 KiB)
julia> @btime _rand_params2(MatrixNormal, Float64, 100, 100);
149.643 μs (25 allocations: 547.73 KiB)
```
> Micro improvements on MatrixNormal

- Project.toml
Supercedes #1205 so that patch version is bumped and new release can be made. @mschauer
> Bump patch and FillArrays minor version

- src/qq.jl
- test/qq.jl
Fixes #1196. I'm not completely sure whether the type parameter of `QQPair` should be widened to `AbstractVector` or `AbstractVector{<:Real}`. I chose the first option for simplicity.
> relax qqbuild signature

- src/univariate/continuous/logitnormal.jl
This PR fixes `gradlogpdf` for `LogitNormal`. Comparison with ForwardDiff:
```julia
using ForwardDiff, Distributions, Plots
plot(x -> gradlogpdf(LogitNormal(), x), xlims=(-0.1,1.1), lab="gradlogpdf", lw=10, ylims=(-500,500))
plot!(x -> ForwardDiff.derivative(y -> logpdf(LogitNormal(), y), x), xlims=(-0.1,1.1), lab="AD(logpdf)", lw=4)
```
produces
And for non-standard parameters:
```julia
μ, σ = 1.0, 2.0
plot(x -> gradlogpdf(LogitNormal(μ, σ), x), xlims=(-0.1,1.1), lab="gradlogpdf", lw=10, ylims=(-50,50))
plot!(x -> ForwardDiff.derivative(y -> logpdf(LogitNormal(μ, σ), y), x), xlims=(-0.1,1.1), lab="AD(logpdf)", lw=4)
```
produces
> Fix gradlogpdf for LogitNormal

- src/multivariate/dirichlet.jl
- test/dirichlet.jl
This fixes `pdf(d::Dirchlet, x)` at the boundary of and outside of the support, and replaces hard-coded Float64 values with more general types.
> Fix #1241; correct the behavior of logpdf(d::Dirichlet, x)

- src/show.jl
This PR reverts https://github.com/JuliaStats/Distributions.jl/pull/1220 which leads to errors for all distributions with fields that are neither of type `NTuple` nor `Array` and do not implement `length` (see https://github.com/JuliaStats/Distributions.jl/pull/1220#discussion_r547174197).
For instance, this leads to errors for `AbstractGPs.FiniteGP` which has a field of type `AbstractGPs.GP` that does not implement `length`.
It would be great if a version with this bugfix could be released soon.
> Revert update of `show`

- src/multivariate/dirichlet.jl
- test/dirichlet.jl
This PR generalizes `Dirichlet` to general `AbstractVector`s of parameters.
This change allows to use `Fill` instead of `fill` for the special case of equal alpha parameter in every dimension, which also simplifies and improves efficiency of computations of `var` and `entropy` as well as sampling. In some places hardcoded `Float64` had to be removed.
> Allow general vectors in `Dirichlet` [BREAKING]

- src/multivariate/mvnormal.jl
- src/multivariate/mvtdist.jl
- test/mvnormal.jl
- test/mvtdist.jl
logpdf should probably return 32-bit results if only 32-bit inputs are provided.
This only fixes it for MvNormal and MvTDist since that's what I'm working with.
Not sure if my tests fit with the current organizational system.
> MvNormal and MvTDist 32-bit logpdf fixes

- Project.toml
Also bumps the patch version so we can tag a release.
> Bump FillArrays dep

- src/matrixvariates.jl
- src/multivariates.jl
This PR is a rebased version of https://github.com/JuliaStats/Distributions.jl/pull/1257 without the deprecations and refactoring that were suggested by @andreasnoack in the previous PR but might require some additional discussion since it implies that some special implementations for evaluating batches of samples (e.g. for `MvNormal`) are removed.
I hope that the subset of changes in this PR are potentially less controversial and hence can be merged faster.
Copied from the original PR:
This PR removes the pre-allocation of output arrays for logpdf and pdf.
There seems little reason to fall back to the in-place methods since it does neither reduce allocations nor lines of code. Instead, I'd argue that the pre-allocation causes problems since the computation of the output type is only a …
> No pre-allocation of outputs for `logpdf` and `pdf`

- Project.toml
- src/matrixvariates.jl
- src/multivariate/dirichlet.jl
- src/multivariate/mvnormal.jl
- src/multivariates.jl
- src/univariate/continuous/normal.jl
- src/univariates.jl
- test/dirichlet.jl
- test/mvnormal.jl
- test/normal.jl
This PR fixes and tests sampling from `Dirichlet` with integer-valued parameters which is broken in 0.24.11 and not tested currently:
```julia
julia> rand(Dirichlet(3, 4))
ERROR: InexactError: Int64(2.581230906529874)
Stacktrace:
[1] Int64 at ./float.jl:710 [inlined]
[2] convert at ./number.jl:7 [inlined]
[3] setindex! at ./array.jl:847 [inlined]
[4] rand!(::Random._GLOBAL_RNG, ::Gamma{Float64}, ::Array{Int64,1}) at /home/david/.julia/packages/Distributions/KDTM8/src/univariates.jl:165
[5] _rand!(::Random._GLOBAL_RNG, ::Dirichlet{Int64,FillArrays.Fill{Int64,1,Tuple{Base.OneTo{Int64}}},Float64}, ::Array{Int64,1}) at /home/david/.julia/packages/Distributions/KDTM8/src/multivariate/dirichlet.jl:162
[6] rand at /home/david/.julia/packages/Distributions/KDTM8/src/multivariates.jl:76 [inlined] …
```
> Fix sampling from distributions with integer-valued parameters (e.g. `MvNormal` and `Dirichlet`)

- Project.toml
- src/multivariate/dirichlet.jl
- test/dirichlet.jl
- test/runtests.jl
This PR fixes https://github.com/JuliaStats/Distributions.jl/issues/1270 that was introduced in https://github.com/JuliaStats/Distributions.jl/pull/1243. I also added tests.
I bumped the version such that a bugfix release can be made available as soon as the PR is merged.
> Fix entropy of `Dirichlet`

- src/univariate/discrete/noncentralhypergeometric.jl
by implementing the method of Liao and Rosen. For the case in https://github.com/JuliaStats/HypothesisTests.jl/issues/224, I saw a 200k times speed up for `cdf` with this change.
> Speed up pdf, cdf, mean, and var for FisherNoncentralHypergeometric

- src/univariate/continuous/uniform.jl
If this is merged, performance for moderately sized calls to rand!() and rand() for a Uniform distribution will be roughly 3x faster (in Julia v1.5.3) than the generic fallback, defined in https://github.com/JuliaStats/Distributions.jl/blob/863844c88e4153af13996f571fcc612d159de542/src/univariates.jl#L163
Current performance:
```julia
julia> @time x = rand(123456);
0.000244 seconds (2 allocations: 964.578 KiB)
julia> @time x = rand(Distributions.Uniform(1,3), 123456);
0.001117 seconds (2 allocations: 964.578 KiB)
julia> @time begin x = Vector{Float64}(undef, 123456); Random.rand!(x) end;
0.000246 seconds (2 allocations: 964.578 KiB)
julia> @time begin x = Vector{Float64}(undef, 123456); Random.rand!(Distributions.Uniform(1,3), x) end;
0.001160 seconds (2 allocations: 964.578 KiB)
``` …
> Add vectorized rand! for uniform distribution

- docs/src/fit.md
- src/univariate/continuous/beta.jl
- test/fit.jl
Included unit tests to check functionality works - ran tests with no errors from my modifications.
Updated documentation too.
> Added Maximum Likelihood Estimation for Beta Distribution (fit_mle)

- src/univariate/continuous/normal.jl
this is really minor thing, this `d.σ` was probably forgotten.
cf. analogous `quantile` above
https://github.com/JuliaStats/Distributions.jl/compare/master...kalmarek:patch-1#diff-b8d201d193aa5a9a28306a5ac259911618261cf3596f9cb557305e2f3fb73ac4L205
> use _σ in cquantile(::Normal, ...)

- src/univariate/discrete/poissonbinomial.jl
- test/poissonbinomial.jl
For many computations, such as e.g. `mean` and `var`, it is not necessary to evaluate the probability mass function of `PoissonBinomial` for all possible outcomes. However, currently, it is computed when `PoissonBinomial` is constructed. For large number of trials this induces a significant delay and might even make it too inefficient to work with `PoissonBinomial` at all.
In this PR, instead the values of the probability mass function are only computed when a user performs an evaluation that requires it.
Simple benchmark on my computer:
```julia
julia> using Distributions, BenchmarkTools, Random
julia> Random.seed!(1234);
julia> p = rand(100);
julia> @btime PoissonBinomial($p);
4.993 μs (1 allocation: 896 bytes)
julia> @btime PoissonBinomial($p; check_args=false);
4.885 μs (1 allocation: …
```
> More efficient `PoissonBinomial`

- src/Distributions.jl
The link to the documentation in the docstring for Distributions.jl leads to an inactive `readthedocs` site. I updated the link to match the one in the README.
> fixed documentation link

- src/univariate/continuous/chi.jl
- test/chi.jl
- test/runtests.jl
Current:
```
julia> mean(Chi(1000))
NaN
```
PR:
```
julia> mean(Chi(1000))
31.614871896968094
```
> make mean(::Chi) more robust

- Project.toml
- src/univariate/continuous/gumbel.jl
- test/gumbel.jl
- test/runtests.jl
On master:
```julia
julia> using Distributions, BenchmarkTools
julia> @btime rand($(Gumbel()));
34.065 ns (0 allocations: 0 bytes)
julia> @btime rand($(Gumbel()), 100);
3.433 μs (1 allocation: 896 bytes)
```
With this PR:
```julia
julia> using Distributions, BenchmarkTools
julia> @btime rand($(Gumbel()));
22.429 ns (0 allocations: 0 bytes)
julia> @btime rand($(Gumbel()), 100);
1.655 μs (1 allocation: 896 bytes)
```
> Faster sampling from `Gumbel`

- Project.toml
- src/univariate/continuous/laplace.jl
- test/fit.jl
The current mle fit for Laplace calculates the mean using the median absolute deviation instead of mean absolute deviation.  The former is not MLE.  Also, I added functionality for a weighted Laplace MLE.
> fix fit for Laplace distribution

- Project.toml
- test/matrixvariates.jl
- test/runtests.jl
This PR removes the test dependency on HypothesisTests.jl and instead uses a custom implementation of the KS test.
The reason for this change is that HypothesisTests.jl introduces a circular dependency: it depends on Distributions.jl and therefore tests fail if a breaking release is prepared (see e.g. https://github.com/JuliaStats/Distributions.jl/pull/1308#discussion_r618720401).
> Remove test dependency on HypothesisTests

- docs/src/univariate.md
as added in #1231
currently its existence is not evident in the docs.
not sure what else (if anything) might need to be done to make its docstring appear in the docs too.
hopefully Documenter takes care f that?
> document Dirac

- docs/src/starting.md
- docs/src/types.md
- src/Distributions.jl
- src/common.jl
When writing generic code that deals with Univariate, Multivariate and Matrixvariate distributions, I often find myself having to code separate methods for each variate type. Having a common supertype `NVariate{N}` should make generic coding for distributions a bit easier.
I propose to introduce `Union{Univariate,Multivariate,Matrixvariate} <: NVariate <: VariateForm` here, instead of changing `VariateForm` to `VariateForm{N}`, to continue leaving room for custom non-scalar/matrix-like variate type (representated by other subtypes of `VariateForm`). [ValueShapes.jl](https://github.com/oschulz/ValueShapes.jl), for example, supports distributions with [`NamedTuple` variates](https://github.com/oschulz/ValueShapes.jl/blob/master/src/distributions.jl#L36).
> Introduce ArrayLikeVariate as common supertype for Univariate, Multivariate and Matrixvariate

- src/univariate/discrete/negativebinomial.jl
- src/univariate/discrete/poisson.jl
- src/univariate/discrete/skellam.jl
Skellam and NegativeBinomial. That will give us three more check marks in the https://github.com/JuliaStats/Distributions.jl/issues/294 list. I'm wondering if we should simply finish the list (in a separate PR) by switching to the inversion method for the remaining distributions. It's really slow but the current situation where the distributions use Rmath when using the global RNG and inversion when an RNG is passed is not good IMO. Ref https://github.com/JuliaStats/Distributions.jl/issues/973
> Switch to using native samplers for Poisson and consequently also

- Project.toml
- docs/src/univariate.md
- src/Distributions.jl
- src/pdfnorm.jl
- test/pdfnorm.jl
- test/runtests.jl
This implements the L2 norm of some distributions, as requested in #806.  I started with continuous univariate distributions for which I was able to work out the integral.  The default method throws an error explaining that the function isn't implemented for the given distribution, but other methods can be added later.  CC: @ablaom @fkiraly
> Add function to compute L2 norm of distributions

- Project.toml
- src/pdfnorm.jl
- test/pdfnorm.jl
> Add squared L2 norms of some discrete distributions

- src/common.jl
Just two minor simplifications.
> Simplify definitions of `variate_form` and `value_support`

- Project.toml
- src/univariate/discrete/poissonbinomial.jl
- test/poissonbinomial.jl
Fixes evaluation of `pdf` and `logpdf` of `PoissonBinomial` with non-integer values (e.g. `Rational`s).
This came up in https://github.com/devmotion/InferenceDiagnostics.jl/pull/7.
> Fix `pdf` and `logpdf`  of `PoissonBinomial`

- src/univariate/discrete/dirac.jl
- src/univariate/locationscale.jl
- src/univariates.jl
- test/dirac.jl
- test/locationscale.jl
This PR fixes the support of `Dirac` and `LocationScale`.
Currently:
```julia
julia> d = LocationScale(1//2, 1//3, Categorical([0.2, 0.8]));
julia> support(d)
1:1
julia> d = Dirac(3.4);
julia> support(d)
3:3
```
With this PR:
```julia
julia> d = LocationScale(1//2, 1//3, Categorical([0.2, 0.8]));
julia> support(d)
5//6:1//3:7//6
julia> d = Dirac(3.4)
Dirac{Float64}(value=3.4)
julia> support(d)
(3.4,)
```
> Fix support of `Dirac` and `LocationScale`

- docs/src/fit.md
- src/univariate/continuous/weibull.jl
- test/fit.jl
I added an implementation that solves for the [Weibull maximum likelihood estimators](https://en.wikipedia.org/wiki/Weibull_distribution#Parameter_estimation) using newtons method. Included some basic tests as sanity checks and updated the docs.
I noticed that there was some discussion in #1267 on whether or not use a generic newtons method and wondering if that's been decided on. 
Merging this can close #702.
> Added mle for weibull distribution

- src/univariates.jl
This PR is an alternative to https://github.com/JuliaStats/Distributions.jl/pull/1281 that does not introduce any additional keyword arguments for `rand!`.
It introduces a function barrier in `rand!(rng, s::Sampleable{Univariate}, ::AbstractArray)` since `sampler(s)` is not type stable e.g. for `Beta` distributions.
On master:
```julia
julia> using BenchmarkTools, Distributions, Random
julia> x = zeros(100_000);
julia> f(x) = rand!(Beta(0.1, 1.0), x);
julia> @benchmark f($x)
BenchmarkTools.Trial: 
memory estimate:  3.04 MiB
allocs estimate:  199490
--------------
minimum time:     18.404 ms (0.00% GC)
median time:      19.938 ms (0.00% GC)
mean time:        20.054 ms (0.38% GC)
maximum time:     23.241 ms (0.00% GC)
--------------
samples:          249
evals/sample:     1
```
With this …
> Add function barrier in `rand!`

- Project.toml
- src/multivariate/mvlognormal.jl
- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
- test/mvlognormal.jl
- test/mvnormal.jl
There are multiple and regular complaints about the current constructors of `MvNormal` (and hence also of `MvNormalCanon` and `MvLogNormal`) being suprising and unintuitive (see, e.g., https://github.com/JuliaStats/Distributions.jl/issues/1203, https://github.com/JuliaStats/Distributions.jl/issues/1333, https://github.com/JuliaStats/Distributions.jl/issues/584, https://github.com/JuliaStats/Distributions.jl/issues/826, https://github.com/JuliaStats/Distributions.jl/issues/657).
This PR implements the suggestion in https://github.com/JuliaStats/Distributions.jl/issues/1203#issuecomment-716165782 and https://github.com/JuliaStats/Distributions.jl/issues/1203#issuecomment-716205791, and deprecates the constructors of `MvNormal` that accept a scalar standard deviation or a vector of standard …
> Deprecate use of vectors + scalars of standard deviations in constructors of multivariate normal distributions

- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
The docstring for `AbstractMvNormal` has outdated definitions of the `MvNormal` struct and its aliases, which is quite confusing when trying to write own methods dispatching on the covariance type. This PR also fixes an outdated link and a minor inconsistency.
> Fix AbstractMvNormal docstring

- Project.toml
- src/Distributions.jl
- src/univariate/discrete/poissonbinomial.jl
- test/poissonbinomial.jl
I am in the process of updating DistributionsAD to ChainRules 1. I thought it would be a good opportunity to reduce the amount of type piracy and move rules for functions in Distributions here. Currently, there's only one such rule in DistributionsAD. It defines the pullback for the pdf of the `PoissonBinomial` distribution, so the PR adds and tests only this rule.
ChainRulesCore 1 is a very lightweight package (see [@oxinabox's comment](https://github.com/JuliaStats/StatsFuns.jl/pull/106#issuecomment-905063473) for more details) and Distributions already depends on ChainRulesCore indirectly via SpecialFunctions and StatsFuns (support for ChainRules was added in version 0.9.10 which was released today). DistributionsAD does not support ChainRulesCore 1 yet, so the definitions in …
> Add ChainRules definitions for pdf of `PoissonBinomial`

- src/univariate/discrete/discretenonparametric.jl
- test/discretenonparametric.jl
Currently, `var` for `DiscreteNonParametric` is not type stable:
```julia
julia> @inferred var(DiscreteNonParametric([0, 1], [0.5, 0.5]))
ERROR: return type Float64 does not match inferred return type Union{Float64, Int64}
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:33
[2] top-level scope
@ REPL[44]:1
```
Also some variables in `skewness` and `kurtosis` can't be inferred. This PR solves the issue by replacing these methods with a call to existing methods in StatsBase for weighted arrays.
> Fix type stability issues of `DiscreteNonParametric`

- src/univariate/continuous/normalcanon.jl
To allow users to quickly check the definition of `NormalCanon` from the REPL.
> Document NormalCanon parametrisation in docstring

- src/univariate/continuous/normalcanon.jl
- test/normal.jl
just as there are `canonform(::Normal)` as well as `meanform(::MvNormalCanon)` and `canonform(::MvNormal)`.
> `meanform(::NormalCanon)`

- Project.toml
- src/Distributions.jl
- src/test_utils.jl
- test/mvnormal.jl
This PR moves the tests for the MvNormal type inside a new module inside Distributions entitled `TestUtils`. The benefit of locating this code here is that it makes it easy for other packages which implement subtypes of `AbstractMvNormal` to run the same tests as Distributions to make them confident that they have implemented Distributions' `AbstractMvNormal` API properly.
This is non-breaking.
I've also sorted a couple of style-related things, but no additional tests have been added / removed.
cc @devmotion
> MvNormal Test Suite inside src

- Project.toml
- src/truncate.jl
- src/truncated/uniform.jl
This PR removes a default fallback for `truncated(d::UnivariateDistribution, lo::Integer, hi::Integer)` which is not needed anymore (possibly due to recent changes in the default implementation of `truncated`).
The main advantage is that it makes it easier to overload `truncated`: currently one has to resolve method ambiguities that arise from the `Integer` fallback (see e.g. https://github.com/JuliaStats/Distributions.jl/pull/1349).
> Remove `truncated(d, ::Integer, ::Integer)`

- Project.toml
- src/deprecates.jl
- src/functionals.jl
- test/binomial.jl
- test/functionals.jl
- test/loguniform.jl
I noticed in https://github.com/JuliaStats/Distributions.jl/pull/1414 that the order of arguments in `expectation` does not follow the general Julia recommendations and style. IMO the function should be the first argument since this would also allow to use the `do` syntax. The PR fixes this issue.
Additionally, I wonder if `expectation` should be exported.
> Change order of arguments in `expectation`

- Project.toml
- docs/src/density_interface.md
- src/density_interface.jl
- test/density_interface.jl
This is non-breaking and keeps support for DensityInterface v0.3.2.
> Support DensityInterface v0.4

- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
The deprecation warning read:
```
┌ Warning: `MvNormal(d::Int, σ::Real)` is deprecated, use `MvNormal(Diagonal(Fill(σ ^ 2, d)))` instead.
```
However, `Fill` is not exported by Distributions and is likely to cause much searching for many readers.
This PR fixes it by using `fill` instead of `Fill`. Another solution would be to `export Fill` in `src/Distributions.jl`.
cc: @devmotion
> Make symbols in deprecation warnings more explicit

- Project.toml
- src/matrix/wishart.jl
- src/multivariate/mvnormal.jl
- test/mvnormal.jl
Fix some bugs in the implementation of `Wishart`. Some of them were uncovered by the recent release of PDMats and cause test failures (see e.g. https://github.com/JuliaStats/Distributions.jl/pull/1428#issuecomment-973238410).
Mostly, this PR fixes many undesired and incorrect promotions and `Float64` literals. Additionally, since `AbstractPDMat <: AbstractMatrix` many explicit calls `Matrix(pdmat)` can be removed which are expensive/allocating e.g. for `ScalMat` and `PDiagMat`.
*Edit:* A similar problem existed for `MvNormal` and caused test errors e.g. in https://github.com/TuringLang/DynamicPPL.jl/pull/309.
> Fix Wishart and MvNormal bugs

- .github/workflows/CI.yml
- .github/workflows/IntegrationTest.yml
@mschauer  This PR adds some integration tests. To me it seemed DistributionsAD would be the most important downstream package, and the one which is easiest to break accidentally.
Requires the following fix in DistributionsAD (which indicates we just broke it again without noticing): https://github.com/TuringLang/DistributionsAD.jl/pull/207.
> Add integration tests

- test/density_interface.jl
- test/locationscale.jl
- test/matrixreshaped.jl
- test/matrixvariates.jl
- test/runtests.jl
This PR fixes deprecations in the tests and the test failures on Julia 1.7.
Since to me it seemed more reasonable to specify relative tolerances in the failing test (the order of magnitude of the resulting norms of matrices is unknown), I replaced the absolute tolerances with relative ones. I checked locally that smaller tolerances lead to (random) test failures.
> Fix deprecations and test errors on Julia 1.7

- Project.toml
- docs/make.jl
- docs/src/convolution.md
- src/convolution.jl
- test/convolution.jl
This PR contains the seemingly uncontroversial changes in https://github.com/JuliaStats/Distributions.jl/pull/1445: A simpler implementation of `convolve(::MvNormal, ::MvNormal)` and documentation of `convolve` (preview: https://juliastats.org/Distributions.jl/previews/PR1452/convolution/).
Hopefully splitting https://github.com/JuliaStats/Distributions.jl/pull/1445 let's us merge and make available these improvements faster.
> Simplify and document `convolve`

- src/univariates.jl
Clarify definition of the median and turn 
```
julia> median(DiscreteUniform(1, 4))
2.5
```
into a bug. Came up in https://github.com/JuliaStats/Distributions.jl/pull/1470#discussion_r783502531
> Clarify definition of the median

- docs/make.jl
By default, Documenter builds the docs with `prettyurls=true`. Locally, this makes the docs non-browsable. This PR adds the [recommended check](https://juliadocs.github.io/Documenter.jl/stable/man/guide/) of the `CI` variable to only turn on `prettyurls` when building the docs on CI.
> Build docs better on local machine

- Project.toml
- src/truncate.jl
- test/truncate.jl
- test/truncated_exponential.jl
- test/truncated_uniform.jl
- test/truncnormal.jl
Removes the deprecations introduced in https://github.com/JuliaStats/Distributions.jl/pull/1489 and adds back some tests, as suggested in https://github.com/JuliaStats/Distributions.jl/pull/1489#issuecomment-1024919526.
Motivation for this PR (copied from https://github.com/JuliaStats/Distributions.jl/pull/1489#issuecomment-1024918778):
> On a second thought, maybe we should revert the deprecations (but keep everything else as is). It seems unnecessary to disallow these choices explicitly, as eg in an optimization algorithm you might converge to infinity. Of course, it should still be recommended to use nothing or kwargs if the infinite/non-existing bound is fixed.
cc: @sethaxen
> Revert deprecations of `truncated`

- src/univariate/continuous/chi.jl
- test/chi.jl
> Fix Chi pdf for x < 0

- Project.toml
- src/multivariate/mvnormal.jl
- src/multivariate/mvnormalcanon.jl
- test/mvlognormal.jl
- test/mvnormal.jl
On master:
```julia
julia> using Distributions, LinearAlgebra, FillArrays
julia> MvNormal(rand(2), Symmetric(Diagonal([1.0,2.0])))
ERROR: MethodError: Cannot `convert` an object of type Symmetric{Float64, Diagonal{Float64, Vector{Float64}}} to an object of type Diagonal{Float64, Vector{Float64}}
julia> MvNormal(Zeros(2), Symmetric(Diagonal([1.0,2.0])))
ERROR: MethodError: Cannot `convert` an object of type Symmetric{Float64, Diagonal{Float64, Vector{Float64}}} to an object of type Diagonal{Float64, Vector{Float64}}
```
On this PR:
```julia
julia> using Distributions, LinearAlgebra, FillArrays
julia> MvNormal(rand(2), Symmetric(Diagonal([1.0,2.0])))
DiagNormal(
dim: 2
μ: [0.1851389943338715, 0.9573799942189535]
Σ: [1.0 0.0; 0.0 2.0]
)
julia> MvNormal(Zeros(2), …
```
> Support MvNormal holding Symmetric{<:Real,<:Diagonal} or Hermitian

- docs/src/starting.md
Fix typo in `starting.md`. Binomial distribution needs both `n` and `p`.
> Fix Typo for Binomial API

- Project.toml
- src/multivariate/mvnormal.jl
- test/mvnormal.jl
Fixes #1518.
Replaces #1524 with a simpler less general but more efficient implementation that avoids potential method ambiguity errors, surprising error messages, and definitions of `-` for incompatible and intentionally unsupported types (such as, e.g., `-(::MvNormal, ::MvNormal)`, `-(::MvNormal, ::Real)` or `-(::MvNormal, ::AbstractArray{<:Real,N})` for `N != 1`.
I checked and currently `MvNormal` is the only multivariate distribution for which addition with vectors is implemented. Hence no other fixes are needed currently. In a future PR probably we should generalize `AffineDistribution` - but even then we would like to keep the definition in this PR in addition to a generic fallback since it avoids unnecessary allocations.
> Add `-(::MvNormal, ::AbstractVector)`

- docs/src/univariate.md
https://github.com/JuliaStats/Distributions.jl/pull/1453 broke the documentation of LocationScale: https://juliastats.org/Distributions.jl/latest/univariate/ This is quite unfortunate since [I explicitly asked whether it still shows up](https://github.com/JuliaStats/Distributions.jl/pull/1453#issuecomment-997017439).
This PR removes the deprecated `LocationScale` from the documentation.
cc: @ParadaCarleton
> Remove documentation for LocationScale

- Project.toml
- src/functionals.jl
- src/univariate/continuous/laplace.jl
- test/functionals.jl
This gives a speedup by over four orders of magnitude.
Before:
```julia
julia> @btime kldivergence(Laplace(0., 1.), Laplace(1., 2.))
31.333 μs (402 allocations: 9.22 KiB)
0.37708690051216676
```
After:
```julia
julia> @btime kldivergence(Laplace(0., 1.), Laplace(1., 2.))
1.500 ns (0 allocations: 0 bytes)
0.37708690114566634
```
> Add analytical formula for KL of two `Laplace`

- Project.toml
- src/univariate/continuous/chi.jl
- src/univariate/continuous/chisq.jl
- test/functionals.jl
Before:
```julia
julia> @btime kldivergence(Chi(2), Chi(3))
39.625 μs (258 allocations: 6.52 KiB)
0.16782559483781825
```
After:
```julia
julia> @btime mykldivergence(Chi(2), Chi(3))
80.877 ns (0 allocations: 0 bytes)
0.1678255948155206
```
and similar for `Chisq`.
> Add analytical formula for KL of two Chi's

- Project.toml
- src/univariate/continuous/logitnormal.jl
- src/univariate/continuous/lognormal.jl
- src/univariate/continuous/normalcanon.jl
- src/univariate/continuous/skewnormal.jl
- test/functionals.jl
Here, I chose to refer back to the `Normal` case.
I tried to use `params` with a splat, but that was slightly slower than using the explicit fields.
Since each field only appears once and the field names of `Normal` are unlikely to change, that should be fine.
> Add analytical formula for KL between `LogNormal`, `LogitNormal`, and `NormalCanon`

- Project.toml
- src/univariate/continuous/uniform.jl
- test/discreteuniform.jl
- test/uniform.jl
Fixes #1253 and adds tests for it. The case of `DiscreteUniform` was already fixed in #1475.
> Fix fitting `Uniform` with `OffsetArray`s

- Project.toml
- src/truncate.jl
- test/truncate.jl
This PR fixes sampling from truncated distributions whose mass (in terms of the original untruncated distribution) is tiny.
Fixes https://github.com/JuliaStats/Distributions.jl/issues/1548.
> Fix sampling from truncated distribution with small mass

- Project.toml
- src/univariate/discrete/bernoulli.jl
- src/univariate/discrete/binomial.jl
- test/fit.jl
Some improvements to `Bernoulli`. Other distributions might benefit from similar changes, but I didn't go through all of them before knowing whether such modifications would be appreciated.
- replace `1:length(x)` with `eachindex(x)` so that it works with more arrays, for instance `OffsetArrays`
- initialize the counters `c0` and `c1` with `zero(eltype(w))` so that they are type-stable (previously they were `Int32/Float64`)
- fix the creation of domain error: the void method `DomainError()` does not exist
- make `BernoulliStats` generic so that it can collect counters of more general type, for instance `ForwardDiff.Dual`
This new version allows for instance
```julia
using OffsetArrays
x = [0, 1]; w = [1., 2.];
ox = OffsetArray(x, 5); ow = OffsetArray(w, 5);
suffstats(Bernoulli, ox, ow) …
```
> Improve Bernoulli and Binomial

- Project.toml
- src/univariate/continuous/uniform.jl
- src/univariate/discrete/bernoulli.jl
- src/univariate/discrete/binomial.jl
- test/fit.jl
As  a follow-up to #1551 and #1557, this PR addresses #1544 for `Bernoulli`, `Binomial`, and `Uniform`.
With this PR `fit(Uniform{Float32}, ...)` etc. will actually estimate a distribution of type `Uniform{Float32}`, regardless of the observations. One can still use `fit(Uniform, ...)` if the parameter type should not be fixed but depend on the type of the observations.
> Respect type of parameters in `fit` for `Bernoulli`, `Binomial`, and `Uniform`

- src/univariate/discrete/negativebinomial.jl
- test/negativebinomial.jl
This solves the first case of #1512.
> Allow sampling `NegativeBinomial` for `p==1`

- Project.toml
- src/univariate/discrete/negativebinomial.jl
- test/negativebinomial.jl
This PR completes #1568. I would like to merge and release the `rrule` for `logpdf` of `NegativeBinomial` therein. However, some requested changes are still missing and so it seemed easiest and fastest to just implement them myself.
I was not sure if I am supposed to push to the original PR directly so I opened a new one. In contrast to the original PR, this PR keeps the changes to the existing tests (e.g. for ForwardDiff) minimal. Moreover, in the original PR not all the branches were tested but only values in the support of the distributions. Due to the `NaN` values obtained outside of the support (in line with finite differencing) I had to add `nans=true` to the tests since otherwise checks of `isapprox(NaN, NaN)` fail.
> Add `rrule` for `logpdf` of `NegativeBinomial` (completes #1568) 

- Project.toml
- src/multivariate/product.jl
- src/product.jl
- test/product.jl
Fixes #1589.
With this PR (and `julia --depwarn=yes`):
```julia
julia> product_distribution(fill(Weibull(), 5))
Product{Continuous, Weibull{Float64}, Vector{Weibull{Float64}}}(v=Weibull{Float64}[Weibull{Float64}(α=1.0, θ=1.0), Weibull{Float64}(α=1.0, θ=1.0), Weibull{Float64}(α=1.0, θ=1.0), Weibull{Float64}(α=1.0, θ=1.0), Weibull{Float64}(α=1.0, θ=1.0)])
julia> Product(fill(Weibull(), 5))
┌ Warning: Product(v) is deprecated, please use product_distribution(v)
│   caller = top-level scope at REPL[5]:1
└ @ Core REPL[5]:1
Product{Continuous, Weibull{Float64}, Vector{Weibull{Float64}}}(v=Weibull{Float64}[Weibull{Float64}(α=1.0, θ=1.0), Weibull{Float64}(α=1.0, θ=1.0), Weibull{Float64}(α=1.0, θ=1.0), Weibull{Float64}(α=1.0, θ=1.0), Weibull{Float64}(α=1.0, θ=1.0)])
```
> Fix deprecation of `Product`

- README.md
- docs/src/extends.md
- docs/src/fit.md
- docs/src/mixture.md
- docs/src/multivariate.md
- docs/src/types.md
- docs/src/univariate.md
- src/Distributions.jl
- src/univariate/continuous/skewedexponentialpower.jl
- src/utils.jl
As part of the JuliaCon hackathon, I have run all the docs through Grammarly. In case of ambiguity (eg, inplace vs in-place), I have googled for the more popular spelling (often picked based on Wikipedia).
There were no changes to active code, ie, only comments or docs were changed.
Examples:
- log-scale --> on a log scale
- inplace --> in-place
- sub type (was inconsistently used) --> subtype
I'm happy to withdraw this PR if it's not helpful.
> Fix mini typos in docs

- src/cholesky/lkjcholesky.jl
- src/matrix/lkj.jl
- test/cholesky/lkjcholesky.jl
- test/matrixvariates.jl
Given the docstrings of `DomainError` and `ArgumentError` shown below, I think a `DomainError` makes more sense here.
```julia
DomainError(val)
DomainError(val, msg)
The argument val to a function or constructor is outside the valid domain.
Examples
≡≡≡≡≡≡≡≡≡≡
julia> sqrt(-1)
ERROR: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
[...]
```
```julia
ArgumentError(msg)
The parameters to a function call do not match a valid signature. Argument msg is a descriptive error string.
```
> Return -Inf in logpdf of LKJCholesky when out of support

- docs/src/univariate.md
- src/univariate/continuous/skewnormal.jl
This PR improves the SkewNormal docs a bit and adds it, along with the Soliton distribution to the documentation. Hopefully this will make them a bit more visible to users of the library.
> Add missing univariate dists to documentation

- src/univariate/continuous/noncentralbeta.jl
- src/univariate/continuous/noncentralf.jl
- src/univariate/continuous/noncentralt.jl
This makes it easier to people to figure out which parameter of the `NoncentralT(ν, λ)` means what, and adds a basic description for the noncentral distributions too.
> Document parameters for noncentral distributions

- src/univariate/discrete/betabinomial.jl
- test/univariate/discrete/betabinomial.jl
Letting α = 0 or β=0 results in many methods (pdf, quantile, rand) failing. Per Wikipedia, α and β should be positive.  https://en.wikipedia.org/wiki/Beta-binomial_distribution.
> Fix argument checks for BetaBinomial

- src/univariate/continuous/pgeneralizedgaussian.jl
Fixed description of PGeneralizedGaussian to be compliant with mathematical formula and implementation (mismatch between μ, α).
The order of function parameters is given on lines 31-33, where it is compliant with math formula in the docs. However, the documentation for this function had mismatch between μ, α symbols, so this fix is fixing it such that the docs comply with math formula and real implementation.
> Fix of PGeneralizedGaussian description

- src/Distributions.jl
- src/cholesky/lkjcholesky.jl
- src/functionals.jl
- src/genericrand.jl
- src/matrix/lkj.jl
- src/test_utils.jl
- src/univariate/continuous/chernoff.jl
- test/testutils.jl
See https://github.com/JuliaLang/julia/issues/48683 for some motivation on this.
`GLOBAL_RNG` can result in reduced performance when compared to the newer `default_rng()` in newer versions of Julia. `default_rng()` is present as early as Juliar 1.3, so switching to `default_rng()` should not be a major issue.
I actually first ran into this issue with `GLOBAL_RNG` while testing a faster vectorized method for `rand(Normal...)`. This pull request by itself does not impact performance significantly, but makes room for others like #1680 .
> Replace `GLOBAL_RNG` with `default_rng()`

- src/univariate/continuous/normal.jl
In the same spirit as #1269, but requires #1679 to be effective.
Before this and #1679:
```julia
julia> @time randn(n);
0.002643 seconds (2 allocations: 9.419 MiB)
julia> @time randn(n);
0.002520 seconds (2 allocations: 9.419 MiB)
julia> @time rand(Normal(0,1), n);
0.008471 seconds (2 allocations: 9.419 MiB)
julia> @time rand(Normal(0,1), n);
0.008220 seconds (2 allocations: 9.419 MiB)
```
After this and #1679:
```julia
julia> @time randn(n);
0.002543 seconds (2 allocations: 9.419 MiB)
julia> @time randn(n);
0.002482 seconds (2 allocations: 9.419 MiB)
julia> @time rand(Normal(0,1), n);
0.002880 seconds (2 allocations: 9.419 MiB)
julia> @time rand(Normal(0,1), n);
0.002934 seconds (2 allocations: 9.419 MiB)
```
Like #1269, this also improves compatibility with CUDA by replacing indexing …
> Add vectorized rand for Normal dist

- src/qq.jl
- test/qq.jl
This fixes https://github.com/JuliaStats/Distributions.jl/issues/1378
The current behavior is dangerous because when `qqbuild` is used for QQ-plots (as 
`Plots.jl` and `Makie.jl` do) the most extreme outliers are not shown.
> Make sure `qqbuild` does not drop min and max value

- src/truncated/normal.jl
- test/truncated/normal.jl
The internal functions used for computing the mean and variance of the truncated normal distribution were implemented using literals like `√2`, which are always `Float64`. However, some branches of the functions based the return type off of the types of the arguments, which needn't be `Float64`. This led to some instability that can be seen via `@code_warntype`. For example, the inferred result of `_tnmom1` for `Float32` inputs was `Union{Float32,Float64}`.
We can instead use the irrational constants defined for square roots of pi and 2 and ratios thereof in order to avoid promoting to `Float64` unnecessarily. This makes the return type concretely inferrable and provides a small performance improvement, about 12% better (-7ns) for `mean` and 14% better (-20ns) for `var` on my machine as …
> Improve type stability for truncated normal moments

- Project.toml
- src/truncate.jl
- src/truncated/normal.jl
- test/truncate.jl
This PR adds support for `nothing` bounds in `Truncated`: While they are supported (and in fact encouraged) by `truncated` for specifying left- or right-truncated distributions, currently they are not stored in `Truncated` as given but instead converted to and saved as `+Inf`/`-Inf`.
This loss of information is not only surprising but also problematic whenever specializations with specialized return types for left- or right-truncated distributions are needed. For instance, one application (in a private repo) is Bayesian inference in which different transformations of the support are required depending on whether the support of a truncated normal distribution is lower- and/or upper-bounded.
The PR uses the same approach (and also some of the code) that is already used for …
> Store `nothing` bounds in `Truncated`

- src/univariate/continuous/chisq.jl
there were a "k" left from the old documentation of the chisq.
this commit changes the "k" to a \\nu, making it consistent with the rest of the distribution.
> Fix wrong parameter on chisq.jl documentation

- src/truncate.jl
- test/truncate.jl
As described in
[#1726](https://github.com/JuliaStats/Distributions.jl/issues/1726), there occur small numbers-big number problems while evaluating quantiles on `Truncated`.
This Fix uses the knowledge on the upper bound of `Truncated` to properly limit the output.
> Fix Wrong quantiles calculated for some Truncated #1726

- src/common.jl
logpdf evalutes the logarithm of the pdf of d at x, not the pdf of d at x.
> Documentation fix

- src/samplers/multinomial.jl
- test/multivariate/multinomial.jl
See issue #1032
This is virtually a copy of  #1033
I forked the code from @darsnack 's repositoty and rebased to master, and ran the tests.
Fixes #1032. Fixes #1733. Closes #1033.
> UPDATED:  Multinomial distribution rand does not support Float32 probability vectors

- Project.toml
SparseArrays.jl is just a test dependency, and Pkg prefers a different order. Aqua.jl keeps complaining about a few ambiguities and two unbound type parameters in product.jl, but for some strange reason I couldn't resolve the unbound type parameters.
> Project.toml cleanup

- src/univariate/discrete/negativebinomial.jl
Remove note about different notation in [Wikipedia](https://en.wikipedia.org/wiki/Negative_binomial_distribution) (no longer true).
> Update docstring of NegativeBinomial

- docs/src/multivariate.md
- src/Distributions.jl
- src/multivariate/mvlogitnormal.jl
- src/multivariates.jl
- test/multivariate/mvlogitnormal.jl
- test/runtests.jl
> Add MvLogitNormal

- Project.toml
- ext/DistributionsTestExt.jl
- src/Distributions.jl
- src/test_utils.jl
This PR moves the test utilities to an extension to make Test an optional dependency on Julia >= 1.9, in the same way as done e.g. for AbstractFFTs.
> Move test utilities to an extension

- src/univariates.jl
Fixes #1813 by updating docstrings as proposed in https://github.com/JuliaStats/Distributions.jl/issues/1813#issuecomment-1872989317:
- documents in what sense `quantile` and friends invert `cdf` and friends
- documents that inputs to `quantile` and friends are probabilities in `[0, 1]` or log-probabilities in `(-Inf, 0]`. (inputs outside of this range would then lead to undefined behavior)
> Clarify definitions of inverse CDF functions

- Project.toml
- src/eachvariate.jl
- test/eachvariate.jl
Currently, the constructor of `Distributions.EachVariate` fails when there are zero variates (along at least one dimension). The PR fixes this problem similar to the approach taken for `Slices` in https://github.com/JuliaLang/julia/blob/38b81562d79dfa44816bd3ce5b249cad87904587/base/slicearray.jl#L43C1-L43C1.
Fixes #1817.
> Fix `eachvariate` with zero variates

- src/univariate/continuous/gumbel.jl
- test/gradlogpdf.jl
The implementation of `gradlogpdf` for the Gumbel distribution has a sign error.
```julia
julia> using Distributions, ForwardDiff
julia> gradlogpdf(Gumbel(3.5, 1.0), 4.0)
-1.6065306597126334
julia> ForwardDiff.derivative(x->logpdf(Gumbel(3.5, 1.0), x), 4.0)
-0.3934693402873666
julia> Distributions.gradlogpdf(d::Gumbel, x::Real) = (-1 + exp((d.μ - x) / d.θ)) / d.θ
julia> gradlogpdf(Gumbel(3.5, 1.0), 4.0)
-0.3934693402873666
```
> Fix typo in Gumbel `gradlogpdf`

- src/samplers/aliastable.jl
doesn't necessary improve all the CI benchmarks, but I think those are kind of artificial. on all of my actual use cases I've tried, it's faster to use an `ifelse` and omit the `@inbounds`
status quo:
```
julia> @benchmark rand($rng, s) setup=(s = AliasTable(normalize(rand(10), 1)))
BenchmarkTools.Trial: 10000 samples with 999 evaluations.
Range (min … max):   7.132 ns … 33.909 ns  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     11.679 ns              ┊ GC (median):    0.00%
Time  (mean ± σ):   11.606 ns ±  1.195 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%
▁ ▂▂ ▃▄▆▁▇▆▂▇▇▂▇█▃▆▅▅ ▃▃         
▁▁▁▁▁▁▁▁▁▁▂▂▂▁▂▂▂▃▃▃▄▄▃▄▆▆▅▇█▆██▇███████████████████▆██▄▅▅▃ ▄
7.13 ns         Histogram: frequency by time        13.8 ns <
Memory estimate: 0 bytes, allocs estimate: 0.
julia> @benchmark rand($rng, s) …
```
> microoptimization on rand(::AliasTable)

- Project.toml
- src/Distributions.jl
- src/samplers/aliastable.jl
- src/samplers/multinomial.jl
- test/samplers.jl
- test/univariate/discrete/categorical.jl
[AliasTables.jl](https://aliastables.lilithhafner.com/dev/) provides a high performance, high precision alias table implementation. This PR switches from the use of StatsBase implementation details to the public API of the AliasTables package. After making that switch, I also re-tuned the sampling threshold for `Multinomial` so that it selects the right algorithm more appropriately.
Benchmarks using [Chairmarks.jl](https://chairmarks.lilithhafner.com) ("a => b" means I got the result "a" when running on master and the result "b" when running on PR branch):
Multinomial sampling (some multinomial changes backed out of this PR, see https://github.com/JuliaStats/Distributions.jl/pull/1848#discussion_r1562783233, #1834. The multinomial bnechamrks here are as of …
> Use a faster implementation of AliasTables

- .github/workflows/CI.yml
- test/univariate/continuous/semicircle.jl
- test/univariate/locationscale.jl
We need a slightly larger sample size when testing DiscreteNonParametric to ensure that empirical moments are close enough to theoretical moments.
The semicircle tests were also vulnerable to changes to the drawn variates so I've switched from MersenneTwister to StableRNGs.
> Fix failing tests on 1.11-beta

- src/univariate/continuous/ksdist.jl
`lfact` has been replaced by `logfactorial` since at least version 1.2 of SpecialFunctions.jl, which is the earliest compatible version with Distributions.jl.
> Replace deprecated lfact(x)

- src/univariate/continuous/gumbel.jl
There is a typo in the `xval` function in `gumbel.jl`. This closes #1858
> fixing error in xval function in gumbel.jl

- src/truncate.jl
- test/truncate.jl
The PR fixes https://github.com/JuliaStats/Distributions.jl/issues/1854 by clamping the `cdf` and `ccdf` of `Truncated` distributions.
> Clamp `cdf` and `ccdf` of `Truncated`

- .github/workflows/CI.yml
- test/univariate/continuous/semicircle.jl
- test/univariate/locationscale.jl
~~In this draft I see if one can achieve something like #1861 without running tests twice if no prerelease is available. Additionally,~~ This PR removes the nightly tests (see #1861), includes a fix for the mac CI setup (see #1856), and switches to julia-actions/cache for caching.
Edit: The PR also includes https://github.com/JuliaStats/Distributions.jl/pull/1862 which fixes tests on Julia 1.11-beta1 (see https://github.com/JuliaStats/Distributions.jl/pull/1862#issuecomment-2133916510).
> Update CI: No nightly tests, improve macOS CI setup + use julia-actions/cache

- src/univariate/continuous/inversegaussian.jl
- test/runtests.jl
- test/univariate/continuous.jl
- test/univariate/continuous/inversegaussian.jl
Closes #1873
Originally I intended to just add `clamp(z, 0, 1)`, but when I found the source of the overflow, I realized there was room for something better.
The original example in the issue, currently:
```julia
julia> d = InverseGaussian(1.65,590)
InverseGaussian{Float64}(μ=1.65, λ=590.0)
julia> cdf(d, 2.)
Inf
julia> exp(logcdf(d, 2.))
0.9998791763271095
```
With this pull request:
```julia
julia> d = InverseGaussian(1.65,590)
InverseGaussian{Float64}(μ=1.65, λ=590.0)
julia> cdf(d, 2.)
0.9998791763271095
julia> exp(logcdf(d, 2.))
0.9998791763271095
```
There is also a backup clamp just in case someone manages to go even further and break the primary fix.
> Fix InverseGaussian cdf overflows

- src/samplers/gamma.jl
- src/univariate/continuous/exponential.jl
- src/univariate/continuous/tdist.jl
- test/univariate/continuous/chisq.jl
- test/univariate/continuous/exponential.jl
- test/univariate/continuous/gamma.jl
- test/univariate/continuous/tdist.jl
> fix type stability of sampling from `Chisq`, `TDist`, `Gamma`

- .github/workflows/CI.yml
A possible alternative to https://github.com/JuliaStats/Distributions.jl/pull/1861 which in its current state seems to test only pre-release versions but not the latest stable release anymore.
> Test pre-release Julia versions

- test/multivariate/mvlognormal.jl
In https://github.com/JuliaArrays/FillArrays.jl/pull/385 I'm working on improving how broadcasting works for FillArrays. One of the changes is that some types may be inferred differently, so e.g.
Currently
```julia
julia> exp.(Zeros(2))
2-element Fill{Float64}, with entries equal to 1.0
```
Proposed:
```julia
julia> exp.(Zeros(2))
2-element Ones{Float64}
```
Currently, in one of the `mvlognormal` tests, this package is explicitly checking for a `Fill`. This PR relaxes this to a `Union{Fill, Ones}` so that the tests pass either way.
> Relax Fill return type in mvlognormal tests

- src/deprecates.jl
This PR marks the `MatrixReshaped` type itself as deprecated, not just its constructor.  That should prevent it from being displayed as the type name in Julia.  (See [this discourse post](https://discourse.julialang.org/t/axes-not-working-on-reshaped-array/118820/2?u=stevengj).)
For example:
```jl
julia> struct Bar{T}; x::T; end
julia> const Foo = Bar{Int}
Foo (alias for Bar{Int64})
julia> Foo(3) # displays alias Foo instead of Bar{Int}
Foo(3)
julia> Base.deprecate(Main, :Foo)
julia> Foo(3) # no longer displays the deprecated Foo type alias
Bar{Int64}(3)
```
> mark the MatrixReshaped type as deprecated

- src/Distributions.jl
- src/deprecates.jl
- test/matrixreshaped.jl
#1893 seems to cause a few deprecation warnings in our tests. This PR tries to fix them.
> Fix deprecation warnings in tests

- src/univariate/discrete/binomial.jl
- test/ref/discrete/binomial.R
- test/ref/discrete_test.ref.json
- test/univariate/discrete/binomial.jl
> Fix `median` for `Binomial` distribution

- src/univariate/discrete/binomial.jl
- test/univariate/discrete/binomial.jl
Fix #1926 by following suggestions therein to reduce avg number of `cdf(Binomial)` evaluations.
> Re-write median(Binomial) to improve speed

- src/univariate/discrete/geometric.jl
Before
```julia-repl
julia> @b Geometric() mean
2.097 ns
julia> @b Geometric() rand
10.762 ns
julia> @b Geometric() var
2.102 ns
julia> @b Geometric() entropy
8.543 ns
julia> @b Geometric() rand(_, 1000)
9.264 μs (3 allocs: 7.875 KiB)
```
1331649
```julia-repl
julia> @b Geometric() mean
1.199 ns
julia> @b Geometric() rand
2.409 ns
julia> @b Geometric() var
1.195 ns
julia> @b Geometric() entropy
1.197 ns
julia> @b Geometric() rand(_, 1000)
1.118 μs (3 allocs: 7.875 KiB)
```
After
```julia-repl
julia> @b Geometric() mean
1.990 ns
julia> @b Geometric() rand
3.516 ns
julia> @b Geometric() var
2.047 ns
julia> @b Geometric() entropy
8.339 ns
julia> @b Geometric() rand(_, 1000)
1.193 μs (3 allocs: 7.875 KiB)
```
In the PR, `rand` uses a substantially different (and simpler) algorithm proposed in …
> Special case Geometric(OneHalf())

- Project.toml
- src/cholesky/lkjcholesky.jl
- test/cholesky/lkjcholesky.jl
For LKJ the mode is only defined (and then identical to the identity matrix) if η > 1: If 0 < η < 1, the identity matrix is a trough of the density, and if η = 1 then it's a uniform distribution of correlation matrices (see e.g. https://mc-stan.org/docs/functions-reference/correlation_matrix_distributions.html#probability-density-function). Therefore for `LKJ` `mode` is defined only if `η > 1`:
```julia
julia> mode(LKJ(1, 0.5))
ERROR: DomainError with 0.5:
LKJ: mode is defined only when η > 1.
Stacktrace:
[1] #545
@ ~/.julia/packages/Distributions/cWeit/src/matrix/lkj.jl:79 [inlined]
[2] check_args
@ ~/.julia/packages/Distributions/cWeit/src/utils.jl:89 [inlined]
[3] #mode#544
@ ~/.julia/packages/Distributions/cWeit/src/matrix/lkj.jl:79 [inlined]
[4] mode(d::LKJ{Float64, Int64})
@ …
```
> Fix `mode` of `LKJCholesky`

- Project.toml
- test/univariate/discrete/negativebinomial.jl
Not sure why CompatHelper didn't make a PR for this.
> Allow ForwardDiff v1

- src/mixtures/mixturemodel.jl
The matrices may not be strided or BLAS-compatible, so it's best to call the generic function and let it delegate to BLAS. Fixes the test failure in `test/mixture.jl` that was seen in https://github.com/JuliaArrays/FillArrays.jl/actions/runs/14423211869/job/40448391642?pr=409
> Use generic `axpy!` instead of calling `BLAS.axpy!`

- src/mixtures/mixturemodel.jl
- test/mixture.jl
The PR reduces allocations of `cov(::MultivatiateMixture)` (addresses a TODO item).
> Reduce allocations of `cov(::MultivariateMixture)`

- src/univariate/continuous/pgeneralizedgaussian.jl
- test/univariate/continuous/pgeneralizedgaussian.jl
Fixes https://github.com/JuliaStats/Distributions.jl/issues/1916.
The PR also improves `cdf` and `ccdf` which fixes even the "naive" evaluation of `log(cdf(...))` in #1916.
> Fix underflow of `logccdf` of `PGeneralizedGaussian`

- Project.toml
- src/multivariate/mvnormalcanon.jl
In PDMats 0.11.35, `invunwhiten!` was added that computes `whiten!` with `inv`erses of `PDMat` matrices.
> More efficient sampling with `MvNormalCanon`

- src/univariate/discrete/skellam.jl
IMO this should be an internal comment and not a public docstring. For users, there's nothing special about `cdf(::Skellam, ::Real)`, so there's no need for a separate docstring. See https://github.com/JuliaStats/Distributions.jl/pull/1985#discussion_r2154641063 for an example of the situation on the master branch.
> Remove docstring for `cdf(::Skellam, ::Real)`

- src/univariate/continuous/lognormal.jl
Quite a few methods for `LogNormal` call and post-process methods for `Normal` distributions. However, currently the outer constructor for `Normal` distributions is used and hence parameter values (mean and standard deviation) are re-checked (to ensure that the standard deviation is non-negative) in every call.
This PR switches to the ~~inner constructor~~ StatsFuns API (see discussion below) to skip these parameter checks. The difference can be seen e.g. in the output of `@code_llvm` and also be observed when benchmarking e.g. `logpdf`:
```julia
julia> using Distributions, Chairmarks
julia> @be rand(1000) map(x -> logpdf(LogNormal(3.1, 2.5), x), _)
Benchmark: 6251 samples with 1 evaluation
min    11.750 μs (3 allocs: 8.062 KiB)
median 12.416 μs (3 allocs: 8.062 KiB)
mean   13.721 μs (3 …
```
> Skip parameter checks when constructing `Normal` distributions for `LogNormal` calculations
