JuliaStats/Distributions.jl

doc/source/mixture.rst
=> fix small typo on mixture.rst

src/univariate/continuous/vonmises.jl
Modifies ```circvar``` and ```cf``` in ```VonMises``` to fix issue #341.
=> Fixes JuliaStats/Distributions.jl#341

src/univariates.jl
Fixes #372, and avoids calling `eval` inside a macro.
Although less specific, LLVM is still able to optimise away most constant calls, e.g.
```
julia> @code_llvm isbounded(Binomial())
define i1 @julia_isbounded_20509(%Binomial) {
top:
ret i1 true, !dbg !1623
}
```
=> Use generic methods for support functions instead of macro-generated ones

src/truncate.jl, src/univariates.jl
Changes to address the issues described in #380.
=> Support method warnings fix and added type arguments

doc/source/univariate.rst
Was thinking of implementing the Poisson Binomial distribution myself when I noticed it had already been done :).
=> Add documentation for Poisson Binomial distribution

test/poissonbinomial.jl
PoissonBinomial distribution has only been tested in the special case where it reduces to the Binomial distribution. These tests also cover the case where the individual success probabilities differ (sum of three Binomial random variables).
=> added PoissonBinomial test for non-Binomial case

src/univariate/continuous/lognormal.jl
Currently it crashes with a DomainError.
=> Change logpdf(LogNormal...) to return -Inf if evaluated outside support

doc/source/univariate.rst, src/Distributions.jl, src/univariate/continuous/normalinversegaussian.jl, src/univariates.jl, test/normalinversegaussian.jl, test/runtests.jl
This needs tests, but I'm at a loss what to do with the new test framework. Is there some explanation how to hook into that?
=> Add Normal-inverse Gaussian distribution

.travis.yml, doc/source/multivariate.rst, doc/source/types.rst, src/common.jl, src/multivariate/dirichlet.jl, src/multivariate/mvnormal.jl, src/multivariate/mvnormalcanon.jl, src/multivariates.jl, src/truncate.jl, src/univariates.jl, src/utils.jl
And enable travis for 0.3 and 0.4.
Also remove some white space.
=> Fix 0.4 deprecation warnings

src/univariate/continuous/generalizedpareto.jl
Tests did not pick this up, so they need to be expanded as well. However, I did not expand test coverage because I read in the issue queue that the tests are in the midst of a re-organization...
=> Fix Gen. Par. cdf and pdf outside the support range

doc/source/univariate.rst
Corrected typos in descriptions of Bernoulli and Negative Binomial Distributions
=> Corrected formulas

src/qq.jl
=> Fix deprecated vcat syntax

src/matrix/wishart.jl
Make wishart.jl support any Real type, not just Float64
=> Make wishart.jl support any Real type, not just Float64

doc/source/univariate.rst
@kmsquire 
Doesn't look like this renders as I expected in the docs
=> fixup the docs

doc/source/univariate.rst, src/Distributions.jl, src/univariate/continuous/generalizedextremevalue.jl, src/univariates.jl, test/generalizedextremevalue.jl, test/runtests.jl
Replaces https://github.com/JuliaStats/Distributions.jl/pull/446
=> Implement generalised extreme value distribution.

src/Distributions.jl
I use this package infrequently and always have to visit readthedocs. This PR is intended to help me (personally :smile:) to get started with just `?Distributions`.
=> Provide module docstring giving a brief API overview

doc/source/mixture.rst
=> Fixed minor error in example

src/truncated/normal.jl, src/univariate/continuous/normal.jl, test/univariates.jl
- for concrete reference in discussion at #430
=> prototype of parameterized Normal distribution

src/univariates.jl, test/REQUIRE, test/continuous.jl
=> Updated: don't automatically promote to Float64 for ContinuousUnivariateDistributions

src/univariate/discrete/noncentralhypergeometric.jl
I don't think we should use `BigInt` internally for computing `Float64` values. The overflow issue can be handled with `lbeta` and other `log` versions.
The `d.ω.^y` factor could also easily underflow in the old implementation. Finally, the `_P` values could become rather large so I've changed it to return the `log` as well and do subtractions before taking the `exp` in `mean` and `var`.
=> Use lbeta instead of redefining binomial to use BigInts.

src/multivariate/multinomial.jl
designed function to be as overflow resistant as possible.  The derivation can be found here:
http://stats.stackexchange.com/questions/207893/entropy-of-the-multinomial-distribution/208075#208075
=> added entropy functionality to multinomial.jl

REQUIRE, src/Distributions.jl, src/genericrand.jl, src/mixtures/mixturemodel.jl, src/multivariate/mvlognormal.jl, src/multivariate/mvnormal.jl, src/multivariate/mvnormalcanon.jl, src/multivariates.jl, src/samplers/vonmisesfisher.jl, test/continuous.jl, test/runtests.jl
=> Make sure pmap on tests rethrows error. Compatibility fixes for v0.5.

src/truncated/normal.jl, test/runtests.jl, test/truncatednormal.jl
Uncomments the truncated Normal sampler by Robert (1995).
=> Fix JuliaStats/Distributions.jl#343

REQUIRE, src/multivariate/mvlognormal.jl, src/multivariate/mvnormal.jl, src/testutils.jl, src/univariate/continuous/laplace.jl, src/univariate/discrete/betabinomial.jl, src/univariate/discrete/noncentralhypergeometric.jl, test/fit.jl, test/mixture.jl, test/mvlognormal.jl, test/mvnormal.jl
We really need some automated way of testing downstream packages when we tag a new release.
=> Fix fit(Laplace) for changes to StasBase.mad

src/multivariate/multinomial.jl, test/multinomial.jl
Attempt to fix #543. I didn't spend the time to figure out the internals of how Multinomial worked but it seemed like when the bounds check was relaxed the resulting behavior was exactly the natural degeneration.
=> allowing Multinomial to work with 0 trials

doc/source/univariate-continuous.rst
Adds the fix in #555 to the docs. @andreasnoack, you said that once this is merged, ReadTheDocs will automatically update?
=> Document fix for logistic formula

src/Distributions.jl, src/multivariate/dirichletmultinomial.jl, src/multivariates.jl, test/dirichletmultinomial.jl, test/runtests.jl
Here is my first pass "everything seems to work" version.  I still need to add MLE stuff and a few more tests, which I should be able to get to tomorrow.
=> WIP: DirichletMultinomial

README.md, REQUIRE, perf/samplers.jl, src/Distributions.jl, src/common.jl, src/edgeworth.jl, src/estimators.jl, src/mixtures/mixturemodel.jl, src/multivariate/mvlognormal.jl, src/multivariate/mvnormal.jl, src/multivariate/mvtdist.jl, src/samplers/obsoleted.jl, src/univariate/continuous/noncentralchisq.jl, src/univariate/discrete/noncentralhypergeometric.jl, src/univariates.jl
Special functions were recently removed from Base and put into the SpecialFunctions.jl package, so this PR introduces a dependency on that package.
=> Introduce dependency on SpecialFunctions

REQUIRE, src/univariate/discrete/discreteuniform.jl
Adds support for passing an rng for DiscreteUniform distributions.
=> Added rng support to discreteuniform.jl with StatsBase v0.15.0.

src/truncate.jl, test/truncate.jl
Add generic type support to truncated distributions.
=> Generic support to truncated dist

src/univariate/continuous/gamma.jl
This only changes the docstring.
=> Make gamma parameters consistent in docs

src/univariate/continuous/noncentralt.jl, test/noncentralt.jl, test/runtests.jl
=> Finish up "fix noncentral-T"

src/Distributions.jl, src/univariate/continuous/locationscale.jl, src/univariates.jl, test/locationscale.jl, test/runtests.jl
I added a generic location-scale distribution.  The unit tests are not fantastic and are probably not project-conforming, but here is the code if you want it.
=> Added a generic location-scale distribution

src/testutils.jl, test/binomial.jl, test/categorical.jl, test/continuous.jl, test/conversion.jl, test/dirichlet.jl, test/dirichletmultinomial.jl, test/edgeworth.jl, test/fit.jl, test/gradlogpdf.jl, test/kolmogorov.jl, test/locationscale.jl, test/matrix.jl, test/mixture.jl, test/multinomial.jl, test/multivariate_stats.jl, test/mvlognormal.jl, test/mvnormal.jl, test/mvtdist.jl, test/noncentralt.jl, test/poissonbinomial.jl, test/quantile_newton.jl, test/runtests.jl, test/samplers.jl, test/truncate.jl, test/univariates.jl, test/utils.jl, test/vonmisesfisher.jl
See #673 and JuliaStats/PDMats.jl#67.
=> Use Compat.Test instead of Base.Test for Julia v0.7 compatibility

docs/src/extends.md, docs/src/mixture.md, docs/src/truncate.md, docs/src/types.md, src/multivariate/mvnormal.jl, src/multivariate/mvnormalcanon.jl, src/qq.jl
manually ran femtocleaner, and manually fixed some dot broadcasts.
=> cleanup some outdated syntax

src/qq.jl, test/qq.jl, test/runtests.jl
only two of those six periods were needed.  i should really field test more thoroughly before submitting a PR.
what unit test could i add to make sure this doesn't happen again?  i don't see QQ being tested at all, and am not sure what it really does.
=> fixup 8ffb14d4

src/common.jl
=> Remove mutable singletons

.travis.yml, src/univariate/continuous/ksdist.jl
There are probably a couple more things lurking. This one was spotted in https://github.com/JuliaStats/HypothesisTests.jl/pull/132.
=> Updates for Julia 1.0

src/empirical.jl, src/mixtures/mixturemodel.jl, src/multivariate/mvlognormal.jl, src/multivariate/mvtdist.jl, src/qq.jl, src/samplers/multinomial.jl, src/samplers/obsoleted.jl, src/univariate/continuous/exponential.jl, src/univariate/continuous/inversegamma.jl, src/univariate/continuous/noncentralf.jl, src/univariate/continuous/normalinversegaussian.jl, src/univariate/continuous/rayleigh.jl, test/dirichlet.jl, test/mixture.jl, test/multinomial.jl, test/multivariate_stats.jl, test/mvtdist.jl
Similar to #757 and #758. This appears to be the last remaining case.
The second commit just fixes whitespace inconsistencies.
=> Fix a couple more missing `undef`s

src/common.jl, test/binomial.jl, test/categorical.jl, test/locationscale.jl, test/mixture.jl, test/poissonbinomial.jl, test/univariates.jl
=> make univariate distributions broadcastable

docs/src/multivariate.md, src/Distributions.jl, src/multivariate/product.jl, src/multivariates.jl, test/product.jl, test/runtests.jl
I proposed this on the Julia slack and didn't get any negative feedback, so thought I would make a PR to test the waters a bit more thoroughly.
The intent is to add a `Product` distribution, which is really just a wrapper around a vector of univariate distributions to make them behave like a multivariate distribution in which each dimension is independent. For example, `Product(Normal.(randn(10), 1))` behaves like a 10-dimensional Gaussian with identity covariance.
I would greatly appreciate feedback regarding whether or not this is something that is of interest and, if it is, regarding what needs to get this PR up to scratch.
=> Proposal: Product distribution.

src/univariate/discrete/betabinomial.jl, test/betabinomial.jl
Merge the work of @freeboson on BetaBinomial logpdf
=> Lbetabinomial

src/univariate/continuous/gumbel.jl
the z in the raised exponential is negative
=> fixed typo in latex of gumbel definition

REQUIRE, src/univariate/continuous/normal.jl, test/continuous.jl
Part of #283. I have hit this issue a few times: it can be very handy, especially for simulation.
See also https://github.com/JuliaStats/StatsFuns.jl/pull/62, which tweaks the underlying functions to be more useful.
=> Allow Normal distribution with zero std deviation

src/univariate/discrete/skellam.jl, test/univariates.jl
Implemented CDF for Skellam based on SciPy one - https://github.com/scipy/scipy/blob/v0.15.1/scipy/stats/_discrete_distns.py
Referring to #852
=> Added cdf for Skellam

src/univariates.jl, test/binomial.jl
=> fix kurtosis

test/runtests.jl
=> reput logit tests

docs/src/fit.md, src/multivariate/dirichlet.jl, src/multivariate/dirichletmultinomial.jl, src/multivariate/multinomial.jl, src/multivariate/vonmisesfisher.jl, src/univariate/continuous/beta.jl, src/univariate/continuous/cauchy.jl, src/univariate/continuous/exponential.jl, src/univariate/continuous/gamma.jl, src/univariate/continuous/inversegaussian.jl, src/univariate/continuous/laplace.jl, src/univariate/continuous/logitnormal.jl, src/univariate/continuous/lognormal.jl, src/univariate/continuous/pareto.jl, src/univariate/continuous/uniform.jl, src/univariate/discrete/bernoulli.jl, src/univariate/discrete/binomial.jl, src/univariate/discrete/categorical.jl, src/univariate/discrete/discretenonparametric.jl, src/univariate/discrete/geometric.jl, src/univariate/discrete/poisson.jl, test/dirichlet.jl, test/dirichletmultinomial.jl, test/fit.jl, test/multinomial.jl, test/vonmisesfisher.jl
=> Fix suffstats and fit_mle with concrete types

test/fit.jl
last PRs #888 broke master, curious scoping bug
=> fix constant

src/univariate/discrete/discretenonparametric.jl, test/discretenonparametric.jl
Apply the trick from @mschauer (https://github.com/JuliaStats/Distributions.jl/issues/872#issuecomment-486580512) to resolve #872.
=> Resolve #872

src/samplers/gamma.jl, test/dirichlet.jl
* Relax T into Real in gamma sampler
=> Relax Gamma Sampler types

Project.toml, src/deprecates.jl
=> probs deprecate bugfix

src/univariate/continuous/biweight.jl, src/univariate/continuous/epanechnikov.jl, src/univariate/continuous/logitnormal.jl, src/univariate/continuous/triweight.jl, src/univariate/continuous/vonmises.jl, test/runtests.jl, test/univariate_bounds.jl
I noticed an issue in the cdf of the Epanechnikov distribution.  The cdf should be
0 for u <= -1
1 for u >= 1
1/2 + (3/4)u - (1/4)u^3 between -1 and 1
Currently it is of the form
1 for u <= -1
0 for u >= 1
1/2 + (3/4)u - (1/4)u^3 between -1 and 1
=> Bounded distribution outside of support checking

src/univariate/continuous/normal.jl, test/normal.jl
=> fix type inference issue for cdf(::Normal, ...)

Project.toml, test/runtests.jl, test/testutils.jl
Imports are getting confusing, limiting the number of packages with vanilla "using P"
=> specific imports

src/mixtures/mixturemodel.jl
=> Fix docstring type signature

.travis.yml, Project.toml, src/deprecates.jl, src/multivariate/dirichlet.jl, src/multivariate/dirichletmultinomial.jl, src/multivariate/multinomial.jl, src/multivariate/mvtdist.jl, src/univariate/continuous/beta.jl, src/univariate/continuous/betaprime.jl, src/univariate/continuous/chi.jl, src/univariate/continuous/chisq.jl, src/univariate/continuous/erlang.jl, src/univariate/continuous/fdist.jl, src/univariate/continuous/gamma.jl, src/univariate/continuous/inversegamma.jl, src/univariate/continuous/tdist.jl, src/univariate/discrete/betabinomial.jl, src/univariate/discrete/noncentralhypergeometric.jl, src/univariate/discrete/poisson.jl, test/dirichletmultinomial.jl, test/matrixbeta.jl
=> Upgrade to SpecialFunctions 0.8

Project.toml, src/multivariate/multinomial.jl, test/multinomial.jl
As documented in:
https://discourse.julialang.org/t/multinomial-accepts-wrong-parameters/30917/4
=> Fix multinomial

docs/src/fit.md, src/univariate/continuous/rayleigh.jl, test/fit.jl
=> Add fit_mle for Rayleigh distribution

src/univariate/discrete/negativebinomial.jl, test/negativebinomial.jl, test/runtests.jl
This will allow us to use AD when fitting `NegativeBinomoal`.
=> Add native logpdf for NegativeBinomial

src/samplers/binomial.jl
=> fix citation

src/univariate/discrete/bernoulli.jl, test/bernoulli.jl, test/runtests.jl
Includes #1046 . I messed up with Git again, so creating a new PR from scratch.
=> Fix type of Bernoulli sample type

src/Distributions.jl, src/multivariate/mvnormal.jl, test/mvnormal.jl
=> Add affine transformations for MvNormal.

test/normal.jl
=> Nan checks

src/truncated/normal.jl, test/truncnormal.jl
Fixes https://github.com/JuliaStats/Distributions.jl/issues/827.
Added more tests to mean and variance of truncated normal.
@pagnani
=> Improve evaluation of variance of truncated normal in the tails

src/univariate/continuous/erlang.jl
=> fix erlang scale typo from #1083

.travis.yml, src/univariate/continuous/arcsine.jl, test/arcsine.jl, test/runtests.jl
gradlog pdf tested against ForwardDiff
=> Added gradlogpdf for Arcsine

src/truncated/normal.jl, test/truncnormal.jl
fix https://github.com/JuliaStats/Distributions.jl/issues/624
=> fix truncnorm with infinite mean

test/mixture.jl
=> Fix condition for running tests

src/multivariate/product.jl, test/product.jl
Fixes https://github.com/JuliaStats/Distributions.jl/issues/1125.
=> Define `eltype` for `Product`

src/mixtures/unigmm.jl, test/mixture.jl
Fixes https://github.com/JuliaStats/Distributions.jl/issues/1121.
=> Fix type instability of UnivariateGMM

Project.toml
FillArrays has been updated to 0.9 with new features but no breaking changes.
=> Bump FillArrays version

docs/src/fit.md
fit_mle not implemented for Beta
=> PR: removed Beta from MLE list in docs

Project.toml
Would it be possible to merge this and tag a new patch release? I would like to use the fix from #1206 in another package.
=> bump patch number

src/univariate/discrete/discretenonparametric.jl, test/discretenonparametric.jl
Fixes https://github.com/JuliaStats/Distributions.jl/issues/1111.
=> Fix sampling from DiscreteNonParametric with integer-valued probs

test/matrixvariates.jl, test/truncate.jl, test/univariates.jl
Just replacement with a simpler expression.
=> dirname(@__FILE__) can be replaced with @__DIR__

src/univariate/continuous/gumbel.jl
* fix an exponent in the Gumbel pdf
* make it explicit that it is the Gumbel maxima distribution (there is also a Gumbel minima)
=> Gumbel distribution documentation improvements

src/utils.jl
This PR updates a doctest which was broken by the update to Julia 1.6.
=> Fix doctest

.gitattributes
On this branch I get
```console
% github-linguist --breakdown
100.00% Julia
Julia:
perf/mixtures.jl
perf/samplers.jl
src/Distributions.jl
src/common.jl
src/conversion.jl
src/convolution.jl
src/deprecates.jl
src/edgeworth.jl
src/estimators.jl
src/functionals.jl
src/genericfit.jl
src/genericrand.jl
src/matrix/inversewishart.jl
src/matrix/lkj.jl
src/matrix/matrixbeta.jl
src/matrix/matrixfdist.jl
src/matrix/matrixnormal.jl
src/matrix/matrixreshaped.jl
src/matrix/matrixtdist.jl
src/matrix/wishart.jl
src/matrixvariates.jl
src/mixtures/mixturemodel.jl
src/mixtures/unigmm.jl
src/multivariate/dirichlet.jl
src/multivariate/dirichletmultinomial.jl
src/multivariate/multinomial.jl
src/multivariate/mvlognormal.jl
src/multivariate/mvnormal.jl
src/multivariate/mvnormalcanon.jl
src/multivariate/mvtdist.jl …
```
=> Ignore non-Julia files for linguist count

src/univariate/discrete/binomial.jl, src/univariate/discrete/geometric.jl, src/univariate/discrete/hypergeometric.jl, src/univariate/discrete/negativebinomial.jl, src/univariate/discrete/poisson.jl
I noticed these while working on #1326. It's been a while since broadcasting was extended like this so these should be fine to drop.
=> Remove unused custom pdf broadcasting

src/univariate/continuous/loguniform.jl, test/loguniform.jl
=> add entropy(::LogUniform)

src/multivariate/dirichlet.jl, test/dirichlet.jl
I believe the current code was a typo and not intentional.
=> Fix precondition for dirichlet_mode

src/univariate/continuous/rayleigh.jl, test/continuous.jl
fix https://github.com/JuliaStats/Distributions.jl/issues/1371
=> Rayleigh cdf always nonnegative

Project.toml, src/univariate/continuous/inversegaussian.jl, src/univariate/continuous/levy.jl, test/univariates.jl
Fixes https://github.com/JuliaStats/Distributions.jl/issues/1479.
=> Fix constructors of `InverseGaussian` and `Levy`

src/truncate.jl, src/truncated/loguniform.jl, src/truncated/uniform.jl, test/loguniform.jl, test/ref/continuous_test.ref.json, test/runtests.jl, test/truncate.jl, test/truncated_exponential.jl, test/truncated_uniform.jl, test/truncnormal.jl
=> Allow specifying non-existant bounds to truncated using nothing

Project.toml, src/quantilealgs.jl, test/mixture.jl
=> Fix `quantile_bisect` with single point in bracketing interval

docs/src/starting.md
=> Add sentence about distribution objects

test/betabinomial.jl, test/runtests.jl
=> Include and update tests for `BetaBinomial`

src/univariate/discrete/geometric.jl, src/univariate/discrete/negativebinomial.jl, test/runtests.jl, test/univariate/discrete/geometric.jl, test/univariate/discrete/negativebinomial.jl, test/univariates.jl
=> fix mgf of NegativeBinomial

docs/src/univariate.md, src/univariates.jl
=> Add `cgf` to documentation

docs/src/extends.md
Is `rand(::AbstractRNG,...)` the right one here?
=> Docs: Creating matrix variate

Project.toml, src/eachvariate.jl, test/eachvariate.jl, test/runtests.jl
=> Chain rule for `EachVariate` constructor

src/multivariate/dirichletmultinomial.jl
Closes #1601 
Latex output image from QuickLatex render:
=> add docstring for `DirichletMultinomial`

test/univariate/discrete/geometric.jl, test/univariates.jl
Otherwise the tests are vulnerable to stuff like https://github.com/JuliaLang/julia/issues/48457.
=> change some floating point equality checks to approximate

src/univariate/continuous/triangular.jl, test/runtests.jl, test/univariate/continuous/triangular.jl
=> fix cdf & pdf for TriangularDist

src/univariate/discrete/categorical.jl, src/univariate/discrete/discretenonparametric.jl, test/univariate/discrete/categorical.jl, test/univariate/discrete/discretenonparametric.jl
Fixes #1675. Fixes https://github.com/JuliaStats/Distributions.jl/issues/1140.
=> Fix comparisons of `DiscreteNonParametric`

src/univariate/continuous/gamma.jl, src/univariate/continuous/normal.jl, src/univariate/discrete/poisson.jl, test/univariate/continuous/gamma.jl, test/univariate/continuous/normal.jl, test/univariate/discrete/poisson.jl
Addresses #1265 partly
- Fixed univariate normal
- Fixed univariate gamma
- Fixed poisson
=> Inbounds Error Fixes for some Univariates

src/Distributions.jl, src/univariates.jl, test/testutils.jl
=> Import Base.in

src/matrix/inversewishart.jl, test/matrixvariates.jl
Fixes https://github.com/JuliaStats/Distributions.jl/issues/1948
Feedback is welcome!
=> Fix inverse wishart constructor with integer ScalMat/PDiagMat

test/namedtuple/productnamedtuple.jl, test/qq.jl
Fixes two warnings that show up in the tests, see e.g. https://github.com/JuliaStats/Distributions.jl/actions/runs/14158228602/job/39660253935?pr=1959 in #1959.
=> Fix warnings in tests

docs/src/univariate.md, src/Distributions.jl, src/common.jl
=> Document and export gradlogpdf.
